### ISSUE TITLE
Make it possible to use single letter as commodity name

### ISSUE THREAD

**Issue by blais** [beancount/beancount#192]
**[Original report](https://bitbucket.org/blais/beancount/issue/192) by Zhuoyun Wei (Bitbucket: [wzyboy](https://bitbucket.org/wzyboy), GitHub: [wzyboy](https://github.com/wzyboy)).**

----------------------------------------

Hi Martin,

this is a similar issue to #138. I recently found out that Beancount currently does not allow single-letter commodity name. A minimal reproducible example:

```
1970-01-01 commodity USD
1970-01-01 commodity V

2017-09-01 open Assets:SingleLetter:X
2017-09-01 open Assets:Trade:Cash USD
2017-09-01 open Assets:Trade:Positions "FIFO"

2017-09-13 * "Buy 10 shares of Visa"
  Assets:Trade:Cash                         -1000.00 USD
  Assets:Trade:Positions                      +10.00 V { 100.00 USD }
```

A bean-check shows:

```
single-letter.beancount:2:       Invalid token: 'V'
single-letter.beancount:10:      Invalid token: 'V'
```

It seems that single-letter account names do not trigger errors any more (line 4) since #138 is resolved, but single-letter commodity names are still not allowed (line 2 and line 10).

Could you please make single-letter commodity possible? I would like to make pull request but I do not know how to write C code...

**Comment by blais** [comment]
**Original comment by Martin Blais (Bitbucket: [blais](https://bitbucket.org/blais), GitHub: [blais](https://github.com/blais)).**

----------------------------------------

Unfortunately this won't be possible. This would result in ambiguity between the flag - that character which comes right after a date - and a currency. Add a _ or other characters to your currency.

**Comment by blais** [comment]
**Original comment by Martin Blais (Bitbucket: [blais](https://bitbucket.org/blais), GitHub: [blais](https://github.com/blais)).**

----------------------------------------

Not feasible.

**Comment by blais** [comment]
**Original comment by Zhuoyun Wei (Bitbucket: [wzyboy](https://bitbucket.org/wzyboy), GitHub: [wzyboy](https://github.com/wzyboy)).**

----------------------------------------

@martin Sorry but I am a little bit confused: in which case does a commodity come right after a date?

**Comment by blais** [comment]
**Original comment by Martin Blais (Bitbucket: [blais](https://bitbucket.org/blais), GitHub: [blais](https://github.com/blais)).**

----------------------------------------

In order to do that I'd have to include some grammar in the lexer (flex supports states). I suppose that might be doable if the flag token is only ever generated after a date token, with some amount of fiddling.

**Comment by blais** [comment]
**Original comment by Martin Blais (Bitbucket: [blais](https://bitbucket.org/blais), GitHub: [blais](https://github.com/blais)).**

----------------------------------------

Reopening, we should try a conditional rule in the lexer to see if this could be done.

**Comment by blais** [comment]
**Original comment by spaetz (Bitbucket: [spaetz](https://bitbucket.org/spaetz), GitHub: [spaetz](https://github.com/spaetz)).**

----------------------------------------

The obvious reason to support 1-letter commodities/currencies is to be able to use "€" :-)

**Comment by blais** [comment]
**Original comment by dan cohen (Bitbucket: [danimalcohen](https://bitbucket.org/danimalcohen)).**

----------------------------------------

Is there a work around for this?

**Comment by blais** [comment]
**Original comment by Martin Blais (Bitbucket: [blais](https://bitbucket.org/blais), GitHub: [blais](https://github.com/blais)).**

----------------------------------------

There is none at the moment.

Another idea might be to support an  exception for currency symbols (there may even be a unicode class of codes for that), whereby currency symbols would be prohibited for use as flags (sounds totally reasonable to me, esp. since flags are already very limited), though it's not super elegant (exceptions, meh). That could work. 

You're welcome to prototype this if you care for it much. (For consideration for inclusion, please add lexer tests (easy) re. flags and those currency symbols.
For Beancount's current lexer support for Unicode, start here and thread through the rest of the codebase:
https://bitbucket.org/blais/beancount/src/487cb9b0248427ac6882889b6b8bcc1665ce393e/beancount/parser/lexer.l#lines-114

**Comment by blais** [comment]
**Original comment by Nathanial Jones (GitHub: [nconantj](https://github.com/nconantj)).**

----------------------------------------

To me, the inability to use a single character commodity is serious problem. When you can buy stocks with single character ticker symbols, such as Visa \(V\) and Macy’s \(M\), the accounting software should be able to support this.  
  
I think the following solution that would NOT cover currency symbols would be ideal:

1. Limit flags to “txn” and single-character printable symbols \(#, !, \*, @, etc.\).
2. Implement a solution that allows single, alphabetic, characters. The minimum would be A-Z in caps, possibly inclusive of lowercase.

This would likely break some people’s files. How many? I have no clue. 

I am not great with lexers and parsers, so it could take me a while to figure it out in code. Barring any objections, primarily due to the potential breakage, I would be willing to dig into this.

**Comment by blais** [comment]
**Original comment by Martin Blais (Bitbucket: [blais](https://bitbucket.org/blais), GitHub: [blais](https://github.com/blais)).**

----------------------------------------

Nathanial: I wouldn’t call it a “serious” problem, at most a minor annoyance, I mean, you could use \_ after the symbol. I’ve faced the same thing \(again, just an annoyance\).

I like your suggestions however; \(1\) perhaps combined with some other quoting  syntax to allow single character flags \(explicitly quoted\). The problem is that it would break the current syntax, so that would be a minor revision.

**Comment by blais** [comment]
**Original comment by cevans (Bitbucket: [cevans](https://bitbucket.org/cevans), GitHub: [cevans](https://github.com/cevans)).**

----------------------------------------

I can think of two ways of resolving this in the lexer without using REJECT:

One would be to use an inclusive start state that is entered after a date, allowing flag recognition, while using a conditional in YY\_USER\_ACTION to push us back to INITIAL \(and a different whitespace pattern in the AFTERDATE state in order to stay in the state until the potential flag\). I don’t _think_ there would be a significant performance penalty for this: it’s adding a step to every lexer action, but it’s only an integer comparison.

The other would be to have a different regex \(eg, `[0-9]{4,}[-/][0-9]+[-/][0-9]+[ \t\r]+[!&#?%PSTCURM]`\) for a date\+flag token, and then separate this in the parser when constructing a transaction.

I’ve played around with both, and both seem to work, though I may be missing something obvious as to why these would be problematic?  If not, the first is probably the better solution, involving minimal changes.

**Comment by blais** [comment]
**Original comment by cevans (Bitbucket: [cevans](https://bitbucket.org/cevans), GitHub: [cevans](https://github.com/cevans)).**

----------------------------------------

Here’s an example of how the first method might work.  This is a significant problem for us.  We are using beancount for an account with multiple single-letter-symbol investments in it; adding \_ after the symbol isn’t actually allowed with the current lexer, and using a modified name would break bean-price and would need specific handling in our importer.

```diff
diff -r c2e308043916 beancount/parser/lexer.l
--- a/beancount/parser/lexer.l  Fri Feb 07 15:04:44 2020 +0000
+++ b/beancount/parser/lexer.l  Fri Feb 07 15:15:11 2020 +0000
@@ -84,6 +84,7 @@
     yylloc->first_column = yycolumn;                    \
     yylloc->last_column = yycolumn+yyleng-1;            \
     yycolumn += yyleng;                                 \
+    if (YY_START == AFTERDATE) BEGIN(INITIAL);     \
   }


@@ -110,6 +111,8 @@
 /* Exclusive start condition for parsing escape sequences in string literals. */
 %x STRLIT

+/* A start condition triggered when a date is found, to allow flags to be recognized. */
+%s AFTERDATE

 ASCII           [\x00-\x7f]
 UTF-8-1         [\x80-\xbf]
@@ -135,6 +138,9 @@
     return EOL;
 }

+<AFTERDATE>[ \t\r]+ {
+  BEGIN(AFTERDATE);
+ }
  /* Ignore whitespace, except when found at the beginning of a line
     and followed by a regular character. This is how we detect an
     initial indent and thus group postings and comments together in
@@ -218,16 +224,14 @@
     beancount.core.flags, in order for round-trips between text and entries to
     be possible. {5307d8fa1e7b}
     */
-[!&#?%PSTCURM] {
-    if ( yy_line_tokens != 1 ) {
-        yylval->character = yytext[0];
-        return FLAG;
-    }
-    else {
-        yy_skip_line();
-        return SKIPPED;
-    }
-}
+<AFTERDATE>[!&#?%PSTCURM]  {
+         yylval->character = yytext[0];
+         return FLAG;
+     }
+^[!&#?%PSTCURM]    {
+         yy_skip_line();
+         return SKIPPED;
+     }

  /* Keywords. */
 txn        { return TXN; }
@@ -288,6 +292,7 @@

     /* Attempt to create the date. */
     BUILD_LEX("DATE", "iii", year, month, day);
+    BEGIN(AFTERDATE);
     return DATE;
 }

@@ -299,7 +304,7 @@

  /* Currencies. These are defined as uppercase only in order to disambiguate the
   * syntax. This is kept in sync with beancount.core.amount.CURRENCY_RE. */
-[A-Z][A-Z0-9\'\.\_\-]{0,22}[A-Z0-9]    {
+[A-Z][A-Z0-9\'\.\_\-]{0,22}    {
     BUILD_LEX("CURRENCY", "s", yytext);
     return CURRENCY;
 }
```

‌

**Comment by cgevans** [comment]
It looks like the migration has the wrong account listed for me, but I've found this.  I can make a pull request for this change if it would be useful.

**Comment by flowerbug** [comment]
I've hit this one recently importing older accounts.  Also, for those doing historical stuff this would be a welcome fix.  Now though that I look into it for historical purposes this is a fun issue because the Symbols have been reused.

**Comment by dnicolodi** [comment]
Single letter commodity symbols are supported in Beancount v3 (current git master branch). This improvement will not be backported to the v2 branch.

**Comment by blais** [comment]
+1

**Comment by cgevans** [comment]
> I've hit this one recently importing older accounts. Also, for those doing historical stuff this would be a welcome fix. Now though that I look into it for historical purposes this is a fun issue because the Symbols have been reused.

I keep an old branch of v2 that supports single-letter commodities (referenced above); although it's only intended for my own use, you might find it useful.  The change is rather simple to implement.

**Comment by dnicolodi** [comment]
@cgevans I think I already commented about this: at a quick look your patch above does not take into account the fact that single postings in a transaction may be marked with flags. Unless I'm not seeing something, your patch removes this aspect of the Beancount syntax completely.

**Comment by cgevans** [comment]
The patch above is old; I've since modified it to support flags on postings.  With that said, it does make some other potentially problematic changes (does not allow flags that are not in beancount.core.flags, does not allow unindented flags at the beginning of the line as a way to make a comment).

**Comment by flowerbug** [comment]
> Single letter commodity symbols are supported in Beancount v3 (current git master branch). This improvement will not be backported to the v2 branch.

Thank you!  :)

**Comment by alensiljak** [comment]
> Single letter commodity symbols are supported in Beancount v3 (current git master branch). This improvement will not be backported to the v2 branch.

I've just tried this with a simple example
```
2025-01-01 open Expenses:Hospitality:Dining
2025-01-01 open Assets:Active:Cash-EUR

2025-05-22 * "Supermarket" "Birthday"
    Expenses:Hospitality:Dining  10 C
    Assets:Active:Cash-EUR  -10 C
```
and am getting an error:
```
test.bean:7:       syntax error, unexpected FLAG, expecting end of file or EOL or ATAT or AT
```

Am I missing something? Thanks.

**Comment by blais** [comment]
The error isn't great but I think commodities with a single character aren't allowed
