### ISSUE TITLE
BitBucket syncing is broken

### ISSUE THREAD

**Issue by adamgibbins** [beancount/beancount#2]
Despite many commits to BitBucket on the default branch since Jan - none appear on GitHub.

**Comment by blais** [comment]
It's not broken, it's not automated, I'm supposed to do this manually.
Evidently, I haven't acquired the discipline yet.
I suggest you switch to the Mercurial repo; 
I'll be pondering whether I should delete that repo or try again.

**Comment by adamgibbins** [comment]
Oops sorry, I thought I read somewhere you'd automated it. I don't use this repo, I do use hg - I just thought this was broken :)
