### ISSUE TITLE
Implement average cost booking

### ISSUE THREAD

**Issue by blais** [beancount/beancount#213]
**[Original report](https://bitbucket.org/blais/beancount/issue/213) by Martin Blais (Bitbucket: [blais](https://bitbucket.org/blais), GitHub: [blais](https://github.com/blais)).**

----------------------------------------

Complete the work on AVERAGE booking method.
See booking_methods.py, at the bottom.
(This is a tracking ticket.)

**Comment by blais** [comment]
**Original comment by YC ..**

----------------------------------------

Hello, it there any update for the average cost booking? I’m looking forward to using this function~

**Comment by blais** [comment]
**Original comment by 孙付 (Bitbucket: [孙付](https://bitbucket.org/孙付)).**

----------------------------------------

@[Martin Blais](https://bitbucket.org/%7Ba1039786-8bf1-4b87-8bed-bcab68bac1bf%7D/) I’d like to know is there any update for this issue. Thanks for your contribution.

**Comment by blais** [comment]
**Original comment by Martin Blais (Bitbucket: [blais](https://bitbucket.org/blais), GitHub: [blais](https://github.com/blais)).**

----------------------------------------

No update

**Comment by russss** [comment]
I may try and take a look at this, for my sins.

Incidentally, in the UK, tax on share sales is calculated on an average cost basis (known as a "section 104 holding"), with a few exceptions if shares are bought and sold in quick succession. So this is fairly important for calculating taxable share sales in the UK.

**Comment by blais** [comment]
https://github.com/beancount/beancount/blob/master/beancount/parser/booking_method.py#L173

**Comment by russss** [comment]
It looks like #591 was rolled back, so I think this issue should be re-opened?

**Comment by Pablo1107** [comment]
Yes, I'm interested in this feature as well, can this issue be re-opened?

**Comment by conan1024hao** [comment]
Any progress on this feature?

**Comment by blais** [comment]
I'm only going to do anything on v3.

**Comment by jrpear** [comment]
I worked around this shortcoming by ignoring Beancount's cost basis tracking and manually inputting the capital gains reported by my broker. They do average cost basis calculation for you. The conversion from the stock to USD is done with a hacky junk account.

My importer gave me something like:

```
2024-09-30 * "YOU SOLD" "[FITLX] "
  Assets:Fidelity:Investment:FITLX           -100.00000 FITLX {} @ 25.780000000 USD
  Income:Capital-Gains:Fidelity:FITLX
  Assets:Fidelity:Investment:USD              2578.0000 USD
  Equity:Rounding-Errors:Imports       0.00212000000000 USD
```

And I had to change it to:

```
2024-09-30 * "YOU SOLD" "[FITLX] "
  Assets:Fidelity:Investment:FITLX                           -100.00000 FITLX
  Income:Capital-Gains:Fidelity:FITLX                           -578.00 USD
  Assets:Fidelity:Investment:USD                              2578.0000 USD
  Equity:Rounding-Errors:Imports                       0.00212000000000 USD
  Equity:StockHackIgnoreMe
```

Where `578.00 USD` came from Fidelity.com under `All Accounts>Positions>Closed Positions>Individual>FITLX>Long-term gain/loss`. Other brokers will probably give this to you too.

**Comment by jerome-tgl** [comment]
Any update of adding the AVERAGE booking method to Beancount v3? In some countries such as France, it's the only legal method for calculating capital gains.

**Comment by blais** [comment]
I'm not working on it. Only thing I'll be working on in the near term is a Rust rewrite (or urgent bugs).

**Comment by d-k-c** [comment]
If someone picked up the work and addressed the performance issue, would you be willing to accept it?

**Comment by blais** [comment]
In v3, sure. I don't recall a performance issue, but a precision issue.
