### ISSUE TITLE
Transaction does not balance with @@: -0.000000000000000000000001

### ISSUE THREAD

**Issue by blais** [beancount/beancount#246]
**[Original report](https://bitbucket.org/blais/beancount/issue/246) by Martin Michlmayr (Bitbucket: [tbm13](https://bitbucket.org/tbm13), GitHub: [tbm](https://github.com/tbm)).**

----------------------------------------

```
2014-01-01 open Assets:Test

2018-03-20 * "Test"
  Assets:Test                42.30 USD @@ 5640 MR
  Assets:Test                            -5640 MR
```

gives

```/home/tbm/beancount/test.beancount:9:       Transaction does not balance: (-1E-24 MR)
```

Clearly it should balance but it doesn't because of rounding when you convert from a total price to a unit price.

Maybe beancount should automatically infer a tolerance of whatever the precsion of the datatype you use to store is.

Also, another argument for issue #194 to somehow store the total price/cost.

**Comment by blais** [comment]
**Original comment by Martin Michlmayr (Bitbucket: [tbm13](https://bitbucket.org/tbm13), GitHub: [tbm](https://github.com/tbm)).**

----------------------------------------

I just noticed I was running an old version.  Anyway, this is still there:

```
Transaction does not balance: (-0.000000000000000000000001 MR)
```

**Comment by blais** [comment]
**Original comment by Martin Michlmayr (Bitbucket: [tbm13](https://bitbucket.org/tbm13), GitHub: [tbm](https://github.com/tbm)).**

----------------------------------------

Issue #384 has another test case for the same issue.

**Comment by blais** [comment]
**Original comment by Martin Blais (Bitbucket: [blais](https://bitbucket.org/blais), GitHub: [blais](https://github.com/blais)).**

----------------------------------------

This is due to inference; working as expected.
If you use bean-doctor context you will see the absence of an inferred tolerance for MR (understandably, there are no digits):


```
#!python

------------ Transaction

2018-03-20 * "Test"
  Assets:Test  42.30 USD @ 133 MR  ; 5639.999999999999999999999999 MR
  Assets:Test  -5640 MR            ;                         -5640 MR


Residual: (-0.000000000000000000000001 MR)
Tolerances: USD=0.005

```

You can get rid of the warning by setting a reasonable default for the inferred tolerance for currency MR:


```
#!python

option "inferred_tolerance_default" "MR:0.00001"

```

**Comment by blais** [comment]
**Original comment by Martin Blais (Bitbucket: [blais](https://bitbucket.org/blais), GitHub: [blais](https://github.com/blais)).**

----------------------------------------

Working as intended.

**Comment by blais** [comment]
**Original comment by Martin Michlmayr (Bitbucket: [tbm13](https://bitbucket.org/tbm13), GitHub: [tbm](https://github.com/tbm)).**

----------------------------------------

I think there are 2 problems here:

1) I have `42.30 USD @@ 5640 MR`, so why does bean-doctor show `42.30 USD @ 133 MR` and not `@ 133.3333` (which it clearly uses internally)

2) I disagree this is invalid.  I specified `@@ 5640 MR`, so it should balance just fine.  As a user, this error doesn't make any sense and is not working as intended.  I know you store things internally in a different way, but this is what's causing the problem.  So I think if the residual is as small as the storage type of this variable, then beancount should automatically ignore it.

As a user, I shouldn't need to specify `inferred_tolerance_default` because the transaction I gave balances 100%. Same with issue #384. The fact that there are two bug reports show that this is not working for users.

**Comment by tbm** [comment]
Can this be opened?

**Comment by felixmde** [comment]
I've just encountered this error and found this issue when migrating from hledger to beancount. I wasn't able to understand what the issue is after reading through this ticket but the [doc on precision tolerances](https://beancount.github.io/docs/precision_tolerances.html) explains it.

I had this transaction:

```
2023-02-13 * "Transfer"
    Assets:Transfers:Checking    5,581.56 EUR @@ 6,000 USD
    Assets:Transfers:Checking                  -6,000. USD
```

which led to this error with bean-check:

```
Transaction does not balance: (0.000000000000000000000001 USD)

   2023-02-13 * "Transfer"
     Assets:Transfers:Checking  5581.56 EUR @ 1.074968288435491153010986176 USD
     Assets:Transfers:Checking    -6000 USD
```

The issue seems to be that having an integer value in the the transaction sets the tolerance to 0. What solved the issue for me was adding two digits after the decimal point like so:

```
2023-02-13 * "TransferWise"
    Assets:Transfers:Checking    5,581.56 EUR @@ 6,000 USD
    Assets:Transfers:Checking                  -6,000.00 USD
```

**Comment by nzbart** [comment]
@felixmde thanks for mentioning the workaround of adding cent digits; that solved the problem for my simple scenario.
