### ISSUE TITLE
Prices are not transitive

### ISSUE THREAD

**Issue by blais** [beancount/beancount#255]
**[Original report](https://bitbucket.org/blais/beancount/issue/255) by Martin Michlmayr (Bitbucket: [tbm13](https://bitbucket.org/tbm13), GitHub: [tbm](https://github.com/tbm)).**

----------------------------------------

If a price pair MR/USD exists as well as USD/EUR, why can't beancount convert from MR to EUR directly?  i.e. why are prices not transitive?  (They are in ledger)

Example:

```
beancount> SELECT CONVERT(position, "USD") WHERE account ~ 'Test' AND currency ~ 'MR'
convert_pos
-----------
 7.5000 USD
-7.5000 USD
beancount> SELECT CONVERT(position, "EUR") WHERE account ~ 'Test' AND currency ~ 'USD'
       convert_position_c_        
----------------------------------
 8.130081300813008130081300813 EUR
-8.130081300813008130081300813 EUR
beancount> SELECT CONVERT(position, "EUR") WHERE account ~ 'Test' AND currency ~ 'MR'
convert_
--------
 1000 MR
-1000 MR
beancount> SELECT CONVERT(CONVERT(position, "USD"), "EUR") WHERE account ~ 'Test' AND currency ~ 'MR'
  convert_convert_position_c__c_  
----------------------------------
 6.097560975609756097560975610 EUR
-6.097560975609756097560975610 EUR
beancount> 
```

Test case:

```
2014-01-01 open Assets:Test

2018-03-20 * "Test"
  Assets:Test                1000 MR
  Assets:Test

2018-03-20 * "Test"
  Assets:Test                10 USD
  Assets:Test

2018-03-25 price EUR 1.23 USD
2018-03-25 price MR 0.0075 USD
```

**Comment by blais** [comment]
**Original comment by Martin Blais (Bitbucket: [blais](https://bitbucket.org/blais), GitHub: [blais](https://github.com/blais)).**

----------------------------------------

That's correct, Beancount will not convert via implicit prices. This is partly for predictability, partly because the correct treatment of implicit prices is not a trivial issue (it has been discussed on the mailing-list previously). I'd be curious to learn how Ledger handles this "generally".

As a compromise, I would consider the explicit insertion of implicit prices for some particular pairs, provided as a configuration option. This would not be ambiguous. However it's not there right now.

**Comment by blais** [comment]
**Original comment by Metin Akat (Bitbucket: [m_akat](https://bitbucket.org/m_akat), GitHub: [loxs](https://github.com/loxs)).**

----------------------------------------

Yeah, it would be troublesome if you have both 

MD/USD <-> USD/EUR   and MD/JPY <-> JPY/EUR - The two most probably wouldn't arrive to the same price for MD/EUR

**Comment by blais** [comment]
**Original comment by Markus Teufelberger (Bitbucket: [MarkusTeufelberger](https://bitbucket.org/MarkusTeufelberger), GitHub: [MarkusTeufelberger](https://github.com/MarkusTeufelberger)).**

----------------------------------------

You can also take a look at https://github.com/beancount/fava/issues/647

Unless "prices" are actually fixed conversion rates, it would be more helpful to being able to specify a price path instead of having Beancount do what might be the right thing or might be completely (or worse: slightly!) off.

Imagine adding a second path (MR --> GBP --> EUR), how should Beancount/ledger decide to convert to USD or GBP to reach EUR?

**Comment by blais** [comment]
**Original comment by Martin Michlmayr (Bitbucket: [tbm13](https://bitbucket.org/tbm13), GitHub: [tbm](https://github.com/tbm)).**

----------------------------------------

I can ask John Wiegley, the author of ledger, how ledger does it exactly.  But I think it's just a graph problem of figuring out the fastest way from A to B. I assume, if you have "MD/USD <-> USD/EUR and MD/JPY <-> JPY/EUR" it would use the price pair that is most recent.  But Metin is correct that it's not obvious how the price was calculated.

I like the idea of a price pair.

Maybe having all prices transitive is not the best idea but there is definitely a strong use case.  For example, I own stocks bought in EUR and GBP but sometimes I just want to see net worth in EUR (or GBP).  I can add prices for some funds<->EUR and for others I'd get fund<->GBP, but I wouldn't have a fund<->EUR mapping for ALL funds.  Being able to say fund<->EUR<->GBP would be useful.  (I know I could nest the CONVERT call, first to GBP, then to  EUR, but that's not ideal.)

**Comment by blais** [comment]
**Original comment by Metin Akat (Bitbucket: [m_akat](https://bitbucket.org/m_akat), GitHub: [loxs](https://github.com/loxs)).**

----------------------------------------

The "latest" algorithm wouldn't help me a lot, as I only fetch conversion rates once towards the end of the month, as it only matters for my monthly graphs. When I do that, all the prices have the same date usually.

So I have my fetcher script explicitly convert eg. STOCK => HKD => EUR => BGN for reporting purposes. If I do STOCK => HKD => BGN directly, numbers differ just slightly from what my brokerage account (denominated in EUR) believes to be the case.

This is because  EUR <> BGN is a fixed rate but BGN <> HKD and EUR <> HKD are not.

**Comment by blais** [comment]
**Original comment by Markus Teufelberger (Bitbucket: [MarkusTeufelberger](https://bitbucket.org/MarkusTeufelberger), GitHub: [MarkusTeufelberger](https://github.com/MarkusTeufelberger)).**

----------------------------------------

I guess the easiest solution would be to be able to define arbitrary paths through currency conversion rates. Specifying two different paths for the same pair would be an error.

**Comment by blais** [comment]
I agree with the explicit solution from this thread: let the user define specific paths to fill in and extrapolate only those, adding them to the price database. 

Moreover, it would be desirable to distinguish between implicitly defined prices (from transactions) and explicitly defined ones (from Price directives). The former should probably be ignored for interpolation.

This is a feature request, not a bug, and nothing's broken; demoting to P2.

**Comment by jpluscplusm** [comment]
Does anyone have a price-generation plugin which can automate any part of this, before a first-class solution emerges? I've got some quite long commodity chains (nothing to do with actual commodities, and more to do with pricing forecasting) which are an absolute pain to keep in sync ...

**Comment by mqnfred** [comment]
Hello friends,

I have come across the same problem, it would be a great feature to have! In the meantime, (cc @jpluscplusm), here is a small script I came up with to generate a table of transitive prices:

```python
#!/usr/bin/env python3


from beancount import loader
from beancount.core.prices import build_price_map
from sys import (argv, exit)


frm = argv[1]
pivot = argv[2]
to = argv[3]


entries = []
for arg in argv[4:]:
    ent, errors, options = loader.load_file(arg)
    if errors:
        print(errors)
        exit(1)
    entries = entries + ent

input_by_date = {}
for (pair, price_points) in build_price_map(entries).items():
    if pair[0] == pivot and (pair[1] == frm or pair[1] == to):
        for (date, price) in price_points:
            if date not in input_by_date.keys():
                input_by_date[date] = []
            input_by_date[date] += [(pair, price)]

left = None
right = None
print("; vim: tw=0 expandtab\n")
for date in sorted(input_by_date.keys()):
    price_points = input_by_date[date]

    for (pair, price) in price_points:
        left = price if pair[1] == to else left
        right = price if pair[1] == frm else right

    if price_points is not [] and left and right:
        print("{} price {} {:.6f} {}".format(date, frm, left / right, to))
```

For example, I want to generate transitive price table for the pair `(UBER, EUR)`. I have the following prices for the pairs `(UBER, USD)` and `(EUR, USD)`:

```
$ cat prices/official/eur-usd.beancount | head
; vim: tw=0 expandtab

2016-01-08 price EUR                           1.09024 USD
2016-01-15 price EUR                          1.090945 USD
2016-01-22 price EUR                           1.07901 USD
2016-01-29 price EUR                           1.08269 USD
2016-02-05 price EUR                          1.114475 USD
2016-02-12 price EUR                          1.125615 USD
2016-02-19 price EUR                           1.11346 USD
2016-02-26 price EUR                            1.0927 USD
$ cat prices/official/uber-usd.beancount | head
; vim: tw=0 expandtab

2019-05-10 price UBER                    41.56999969482422 USD
2019-05-17 price UBER                    41.90999984741211 USD
2019-05-24 price UBER                     41.5099983215332 USD
2019-05-31 price UBER                    40.40999984741211 USD
2019-06-07 price UBER                    44.15999984741211 USD
2019-06-14 price UBER                    43.22999954223633 USD
2019-06-21 price UBER                                 44.0 USD
2019-06-28 price UBER                   46.380001068115234 USD
```

Given a set of `(from, pivot, to)` currencies, and price directives between `(from, pivot)` and `(pivot, to)`, this script will generate the transitive price map between `(from, to)`:

```
$ prices/gen-transitives.py UBER USD EUR prices/official/*.beancount | head
; vim: tw=0 expandtab

2019-05-10 price UBER 37.012469 EUR
2019-05-17 price UBER 37.555951 EUR
2019-05-24 price UBER 37.032079 EUR
2019-05-31 price UBER 36.168194 EUR
2019-06-07 price UBER 38.943516 EUR
2019-06-14 price UBER 38.574449 EUR
2019-06-21 price UBER 38.701733 EUR
2019-06-28 price UBER 40.766280 EUR
```

This is my first time writing python for beancount, the script is definitely sub-optimal and probably does not leverage properly the beancount library, but it works!

**Comment by jpluscplusm** [comment]
Thanks, @mqnfred! I had written something similar, albeit just using AWK, hence no python or beancount :-)

I've pushed it here: https://github.com/jpluscplusm/beancount-transitive-price-calculator

**Comment by blais** [comment]
I started to implement this to resolve another issue I have - converting the net-worth script away from using beancount.ops.holdings - and I've come to realize that properly doing this would have to insert price conversions when the rate changes so, so if there are N prices and M rate, you'd end up inserting O(N*M) new entries in the price database. For example, if you had this:

2019-05-10 price UBER                    41.56999969482422 USD
2019-05-17 price UBER                    41.90999984741211 USD
and
2019-05-13 price USD   1.5 EUR

to do this correctly, you'd have to insert new prices for UBER in EUR at dates 5/10, 5/13 (when the rate changes) and 5/17. In other words, when the rate changes, the price point of all the affected currencies do to.

It would be more frugal to perform this at runtime upon looking up a value. In other words, do two lookups instead of one, with a specialized conversion routine, instead of explicitly representating all combinations.

In any case, I'll probably check my "projection" code that projects the prices points at their date, with comments about this limitation.

**Comment by blais** [comment]
https://github.com/beancount/beancount/blob/v2/beancount/core/prices.py#L138

**Comment by nolith** [comment]
How can I use the`beancount.core.prices.project()` api to get this transitive price map?

The script provided in https://github.com/beancount/beancount/issues/255#issuecomment-678406642 seems more usable at this stage.

**Comment by James-E-A** [comment]
A silly use-case I have: I'd like to be able to view my net value and savings over time in ounces-of-gold to be more inflation-minded

```ini
include "lbma_gold_pm.beancount"
option "operating_currency" "AU-TOZ"
```

> I would consider the explicit insertion of implicit prices for some particular pairs, provided as a configuration option.

I haven't kicked the tires on the plug-in API *yet*, but from [reading the documentation](https://beancount.github.io/docs/beancount_scripting_plugins.html#load-pipeline) it looks like injecting synthetic transitive prices shouldn't be too hard to cook up a plugin for, as a workaround.

**Comment by James-E-A** [comment]
@nolith `project()` is something more complex than what’s actually needed for this use-case; you simply need to call something like

```python
# 1. HOOL -> 2. USD
currency1 = entry.currency
currency2 = entry.amount.currency
conv_1_2 = entry.amount.number

# 2. USD -> 3. GBP
conv_2_3 = get_price(orig_price_map, (currency3, currency2), entry.date)[1]
assert conv_2_3 is not None, f"Unable to look up {currency} in terms of {currency3} because there is no intermediate entry putting {currency2} in terms of {currency3}"

# 1. HOOL -> 3. GBP
conv_1_3 = conv_1_2 / conv_2_3
yield Price(
	meta=entry.meta,
	date=entry.date,
	amount=Amount(currency=currency3, number=conv_1_3),
	currency=currency1
)
```

https://gist.github.com/24d7668223964a6f8d60ce1b2ea3a4fa
