### ISSUE TITLE
Enable a CI solution; try Atlassian's Pipelines

### ISSUE THREAD

**Issue by blais** [beancount/beancount#269]
**[Original report](https://bitbucket.org/blais/beancount/issue/269) by Martin Blais (Bitbucket: [blais](https://bitbucket.org/blais), GitHub: [blais](https://github.com/blais)).**

----------------------------------------

Enable a CI solution; try Atlassian's Pipelines

**Comment by dnicolodi** [comment]
This issue can be closed.
