### ISSUE TITLE
Trailing whitespace when printing with price

### ISSUE THREAD

**Issue by blais** [beancount/beancount#273]
**[Original report](https://bitbucket.org/blais/beancount/issue/273) by droogmic (Bitbucket: Michael Droogleever, GitHub: [droogmic](https://github.com/droogmic)).**

----------------------------------------

To reproduce:

```python
>>> from beancount.parser import printer
>>> from beancount.core import data
>>> import datetime as dt
>>> p1 = data.Posting("Account", data.Amount.from_string("10.00 CHF"), None, data.Amount.from_string("1 USD"), None, None)
>>> p2 = data.Posting("Account", data.Amount.from_string("-10.00 USD"), None, None, None, None)
>>> t = data.Transaction(None, dt.date(2017,1,1), '*', "", "Narration String", data.EMPTY_SET, data.EMPTY_SET, [p1, p2])
>>> print(printer.format_entry(t).replace(' ', '~'))
2017-01-01~*~"Narration~String"
~~Account~~~10.00~CHF~@~1~USD
~~Account~~-10.00~USD~~~~~~~~
```

The second posting has trailing whitespace to match  the length of price, but this causes a visual warning in many IDEs for trailing whitespace. e.g. in fava.

**Comment by josephw** [comment]
Was this fixed by 3fac7f760 ?

**Comment by blais** [comment]
You can verify by running the code above. Let me know.

**Comment by josephw** [comment]
I'm no longer able to reproduce it. Output running current `v2` is:

```
2017-01-01~*~"Narration~String"
~~Account~~~10.00~CHF~@~1~USD
~~Account~~-10.00~USD
```

**Comment by blais** [comment]
thank you
