### ISSUE TITLE
Is it possible to exclude unnecessary deps?

### ISSUE THREAD

**Issue by blais** [beancount/beancount#286]
**[Original report](https://bitbucket.org/blais/beancount/issue/286) by Limbo Peng (Bitbucket: [iwinux](https://bitbucket.org/iwinux), GitHub: [iwinux](https://github.com/iwinux)).**

----------------------------------------

Hi,

Seems that there're many deps that get installed but I never use those related features, e.g.:

1. `google-api-python-client` (I don't upload stuff to Google Spreadsheet)
2. `beautifulsoup4` (I don't import XML docs)
3. `lxml` (same as above)

It would be great if these packages are specified in `extra_requires` instead of `install_requires` (to make `pip install` much faster) . What do you think?

**Comment by trim21** [comment]
should we close this now?
