### ISSUE TITLE
Is the parser thread-safe?

### ISSUE THREAD

**Issue by blais** [beancount/beancount#294]
**[Original report](https://bitbucket.org/blais/beancount/issue/294) by Ethan Glasser-Camp (Bitbucket: [glasserc](https://bitbucket.org/glasserc), GitHub: [glasserc](https://github.com/glasserc)).**

----------------------------------------

I just had some baffling errors from fava, where my beancount file (which was accepted by bean-check) was rejected by fava, sometimes to such a drastic extent that a seg fault occurred. I eventually got the problems to go away by closing the several fava tabs I still had opened. fava is running in a threaded manner, and as each browser tab checks every second or so to see if anything's changed, this can lead to re-parsing the file several times simultaneously. My hypothesis is that the parser doesn't support running in different threads and this is the source of the crash.

If the parser is known not to be thread-safe and it seems like too much work to convert it, then one fix might be to change fava to run using ForkingWSGIServer instead of ThreadedWSGIServer. I thought I would find out here first before opening an issue on the fava repository.

**Comment by blais** [comment]
**Original comment by Martin Blais (Bitbucket: [blais](https://bitbucket.org/blais), GitHub: [blais](https://github.com/blais)).**

----------------------------------------

The parser is not thread-safe but it would be easy to put a mutex around the non-thread safe portion only.

**Comment by blais** [comment]
@glasserc 
Hi Ethan, did this issue get resolved?
While the parser is not thread-safe, I'm not explicitly releasing the GIL from the C code and if you're running within the same interpreter this should guarantee calls are serialized, so it should naturally be only running a single parser at a time.
OTOH, If your server runs multiple embedded interpreters in the same process you would have to place a mutex around them. 

Please reopen and let me know if you need me to add this.

Note: The v3 parser will be thread-safe and UTF8 compliant (bison-c++ complete with a reflex scanner)

**Comment by glasserc** [comment]
Hi, I think closing this is the right move. I no longer remember what this was about or what the errors were that I was encountering. Thanks for beancount! I'm excited to see that it's on Github now!
