### ISSUE TITLE
Update documentation for Emacs as minor mode (was: Where is the minor mode for emacs?)

### ISSUE THREAD

**Issue by blais** [beancount/beancount#412]
**[Original report](https://bitbucket.org/blais/beancount/issue/412) by Sven (Bitbucket: [Sven](https://bitbucket.org/Sven), GitHub: [Sven](https://github.com/Sven)).**

----------------------------------------

I'm not able to get beancount emcas mode and orgmode running at the same time. I tried to add the following to `~/.emacs`:

```
(add-to-list 'load-path "/usr/elisp/")
(require 'beancount)
(add-to-list 'auto-mode-alist '("\.beancount\'" . beancount-mode))
```

And my beancount file starts with:

```
;; -*- mode: org; mode: beancount; coding: utf-8; fill-column: 400; -*-
```

Beancount works as expected. However, orgmode is not applied. If I remove `~/.emacs` orgmode works as expected, but not beancount.

After fiddeling around I recognized that in [https://bitbucket.org/blais/beancount/src/tip/editors/emacs/beancount.el](https://bitbucket.org/blais/beancount/src/tip/editors/emacs/beancount.el) it is tsatet, that it is an major mode. The documentation tells it is an minor mode and also on the Github mirror I found the file mentioning minor mode: [https://github.com/beancount/beancount/blob/master/editors/emacs/beancount.el](https://github.com/beancount/beancount/blob/master/editors/emacs/beancount.el)

So my question is, how do I get orgmode and beancount mode working together?

**Comment by blais** [comment]
**Original comment by Daniele Nicolodi (Bitbucket: [daniele](https://bitbucket.org/daniele), GitHub: [dnicolodi](https://github.com/dnicolodi)).**

----------------------------------------

The documentation is outdated, we made `beancount-mode` a major mode a little while ago. You can use `outline-minor-mode` to have \(what was deemed to be a sufficient\) subset of the functionality enabled by `org-mode`. This has been discussed multiple times on the mailing list. Please refer to the mailing list archives for details, untill I find the time to update the documentation. The github mirror is also outdated, apparently.

**Comment by blais** [comment]
**Original comment by Sven (Bitbucket: [Sven](https://bitbucket.org/Sven), GitHub: [Sven](https://github.com/Sven)).**

----------------------------------------

Thanks for the hint. Just referencing a good thread on that topic for others who stumble on this problem:

[https://groups.google.com/d/msg/beancount/B1YA2n7r8SE/Z0lAQxAKCQAJ](https://groups.google.com/d/msg/beancount/B1YA2n7r8SE/Z0lAQxAKCQAJ)

**Comment by dnicolodi** [comment]
I updated the documentation. I think this bug can be closed now.
