### ISSUE TITLE
Support utf-8 account name

### ISSUE THREAD

**Issue by blais** [beancount/beancount#423]
**[Original report](https://bitbucket.org/blais/beancount/issue/423) by 星辰 葛 (Bitbucket: [gexingchen](https://bitbucket.org/gexingchen), GitHub: [gexingchen](https://github.com/gexingchen)).**

----------------------------------------

When I open account with chinese characters like below:

```
2019-01-01 open Assets:银行:招商银行借记卡 CNY
```

Fava will report error:

```
ValueError: Invalid account name: Assets:银行:招商银行借记卡
```

I really want to use chinese account name, would you please make beanaccount support utf-8 account names?

**Comment by blais** [comment]
**Original comment by Justus Pendleton (Bitbucket: [hoostus](https://bitbucket.org/hoostus), GitHub: [hoostus](https://github.com/hoostus)).**

----------------------------------------

Hm, it looks like account.ACCOUNT\_RE is what does the validation. And it seems to contain a hardcoded list of “letters”, “uppercase letters”, and “numbers” that are allowed. I assume those are all Latin-ish options and that’s why it fails. Presumably Korean & Japanese & Thai & Russian & cetera would fail as well?

I don’t know the theory behind the validation constraint so it is hard to propose an alternative off the top of my head :disappointed:

**Comment by blais** [comment]
**Original comment by Zhiyuan Zheng (Bitbucket: [zhzy0077](https://bitbucket.org/zhzy0077), GitHub: [zhzy0077](https://github.com/zhzy0077)).**

----------------------------------------

It’s hard to propose a regular expression suitable for all languages. As a temporary workaround, I removed those validations and build a customized version of beancount. If you prefer, you can take a look at the commit [https://github.com/zhzy0077/beancount/commit/2b5976830b3d367f58651d7d63ef82612bd8474c](https://github.com/zhzy0077/beancount/commit/2b5976830b3d367f58651d7d63ef82612bd8474c). It works fine for me.

**Comment by blais** [comment]
**Original comment by Martin Blais (Bitbucket: [blais](https://bitbucket.org/blais), GitHub: [blais](https://github.com/blais)).**

----------------------------------------

If it’s any consolation, the next rewrite of Beancount will have full support Unicode natively. I’ve had to do some prototype for something since I wrote that and I used RE-Flex which works quite nicely.

**Comment by dallaslu** [comment]
This works:
```beancount
2019-01-01 open Assets:CN:银行:招商银行借记卡 CNY
```

**Comment by blais** [comment]
> This works:
> 
> ```
> 2019-01-01 open Assets:CN:银行:招商银行借记卡 CNY
> ```

On `master` or `v2`?

**Comment by dallaslu** [comment]
> On `master` or `v2`?

`V2`
