### ISSUE TITLE
How to use one commodity in each account?

### ISSUE THREAD

**Issue by SmartHypercube** [beancount/beancount#438]
Hi, I noticed that you recommend using only one commodity in each account in multiple documents. There is even a plugin built for checking this rule. But I am still not sure how to do that, and why.

(Background: I trade many kinds of crypto coins and use them occasionally.)
As far as I can see, it is easy to use one commodity in each Assets/Liabilities account. But enforcing this rule for Equity/Income/Expenses accounts is not practical. Equity:OpeningBalances can easily get multiple commodities, but I see no benefit setting up a sub-account for each of them. Same goes for Income and Expenses accounts. For example, I have an account called Expenses:Gifts, for all kinds of small gifts I give to my friends. If I use "onecommodity" plugin, my ledger and report will quickly be bloated with per-commodity sub-accounts.

Aside from being able to check the balance of multi-commodity accounts, could you please tell me more benefits of using one commodity in each account? Thanks!

**Comment by blais** [comment]
For investments or trading accounts, it can make it easier to filter the action around a single stock by using the name of the stock as the leaf of the account name.

The "onecommodity" plugin needs an update to allow it to skip accounts that have declared multiple commodities in their Open directive.

**Comment by blais** [comment]
Fixed in https://github.com/beancount/beancount/commit/05290ba6a3db42f389d98f65f74afe41b8a6ab64

The options there should allow you to configure as desired.
