### ISSUE TITLE
Support Spaces in Account Names

### ISSUE THREAD

**Issue by kaiwei** [beancount/beancount#462]
Instead of Expenses:ShippingCharges, it will be so much more legible if we can do Expenses:Shipping Charges. Or Income:Capital Gains instead of Income:CapitalGains

Is there any way we can add this support?

**Comment by blais** [comment]
No. This adds no additional functionality and it will make potential future changes to the grammar/lexer more tricky for no great gain.
There are many more pressing things to fix in front of that.  
I'm not going to add this in v2, and probably not in v3 either.

**Comment by xuhcc** [comment]
@kaiwei I'm using hyphens in place of spaces, e.g. `Expenses:Shipping-Charges`
