### ISSUE TITLE
Transfers equity between accounts and cost basis

### ISSUE THREAD

**Issue by chaoxu** [beancount/beancount#476]
I have multiple brokerages, and sometimes transfer equities between them, in a FIFO fashion.
I also buy/sell gift cards (which is a commodity), and might redeem them into different accounts. So the cost basis should also carry over. 

I don't think there is a way to carry the cost basis information around automatically. I can't just add `{}` and something magically happens.

The following is an example where I switched my brokerage, where I defined all lots are FIFO.
```
2020-01-01 * "Buy" "STOCK"
  Assets:Brokerage1  10 STOCK {10.00 USD}
  Assets:Brokerage1  10 STOCK {1.00 USD}
  Assets:Brokerage1  -110.00 USD

2020-01-02 * "Transfer" "Transfer Brokerage"
  Assets:Brokerage1  -15 STOCK {}
  Assets:Brokerage2  15 STOCK

2020-01-02 * "Sell" "Sell STOCK"
  Assets:Brokerage2  -10 STOCK {} @ 100.00 USD
  Assets:Brokerage2  1000 USD
  Income:PnL
```

The above would give an error. It would be nice if there are ways to specify the transferring of cost basis if the commodity matches in a FIFO fashion(actually, average cost is fine too, as long as there is some way to move that information around in an automated way).

**Comment by blais** [comment]
I think there's a bug there.

Before that,
you'll want to change this:

  Assets:Brokerage1  -110.00 USD

to go to a cash account so it doesn't get in the way of automated FIFO
matching.
e.g.

  Assets:Brokerage1:Cash  -110.00 USD

Second, you'll have to indicate that those accounts are to be handled
with FIFO, e.g.
2019-12-31 open Assets:Brokerage1   "FIFO"
2019-12-31 open Assets:Brokerage2   "FIFO"

With these changes, the error I get is:
/home/blais/r/q/beancount-data/user/chaoxu/transfer-equity-fifo.beancount:10:
     No position matches "Posting(account='Assets:Brokerage1', units=-15
STOCK, cost=CostSpec(number_per=<class 'beancount.core.number.MISSING'>,
number_total=None, currency='STOCK', date=None, label=None, merge=False),
price=None, flag=None, meta={'filename':
'/home/blais/r/q/beancount-data/user/chaoxu/transfer-equity-fifo.beancount',
'lineno': 11})" against balance (10 STOCK {1.00 USD, 2020-01-01}, 10 STOCK
{10.00 USD, 2020-01-01})

The potential bug I see here is that the CostSpec()'s currency is set to
STOCK, where as you didn't provide any in your reduction ({}). This should
be matched FIFO against the two lots from 1/1. I'll file a ticket.
It can be resolved by inserting a cost currency, replacing the erroneous
default STOCK to an explicit USD, like this

2020-01-02 * "Transfer" "Transfer Brokerage"
  Assets:Brokerage1  -15 STOCK {USD}
  Assets:Brokerage2  15 STOCK

Now this won't balance:
/home/blais/r/q/beancount-data/user/chaoxu/transfer-equity-fifo.beancount:10:
     Transaction does not balance: (-105.00 USD, 15 STOCK)

   2020-01-02 * "Transfer" "Transfer Brokerage"
     Assets:Brokerage1  -10 STOCK {10.00 USD, 2020-01-01}
     Assets:Brokerage1   -5 STOCK {1.00 USD, 2020-01-01}
     Assets:Brokerage2   15 STOCK

For good reason: the weight of the first two postings is in USD.
There's no way to use interpolation to let it attach the cost bases from
the selected postings (it's not that smart).

**Comment by blais** [comment]
https://github.com/beancount/beancount/issues/481
