### ISSUE TITLE
Require bison 3.6?

### ISSUE THREAD

**Issue by dnicolodi** [beancount/beancount#478]
@blais, how do you feel about requiring Bison 3.6 to generate the beancount parser? So far no minimum required version has been specified, and I kept using 3.4 as this was the version used to produce the generated files in the repository. However, 3.6 introduces several nice improvements that would benefit the code. I see that you require Bison 3.6 for Oblique and use some of the new features. Is there any reason to keep the beancount parser definition compatible with older Bison versions?

**Comment by blais** [comment]
No particular reason, happy to update the generated code.
I'm using 3.6.3 (I think) because I had a fix made to it by Akim.
With Bazel I have freedom to bump versions anytime, which is nice.

Generally for the v2 checked in version it's nice to stick with the version from latest of the Ubunbu LTS versions if possible.

**Comment by dnicolodi** [comment]
I think that if the generated code is kept in the repository there isn't much to gain sticking with an old version of the tools: users would compile from the already generated code and developers can be required to work with modern tooling. Is the latest Ubuntu LTS relevant for the CI infrastructure?

Bison is at version 3.5.1 in Ubuntu 20.04. Bison 3.6 goes several steps in making error reporting from the lexer to the grammar not completely broken and I would like to profit from them.

**Comment by blais** [comment]
Yeah I don't care that much about the version.

I'm moving in two weeks and still working 60hrs/wk with child at home. I'm not going to have much time to review code, especially parser changes which I'd rather hold off until I merge the Bazel branch. I would keep any such proposals (a) very small and focused, and (b) well isolated (so I don't have to merge a huge amount of changes, which if the PR is too large may never happen). If the changes are too big, I may not be able to merge them with the v3 changes. Keep it small and isolated.

**Comment by blais** [comment]
Fixed in 240bc11723ecd00a9202abfb65b03ae4aca92284
