### ISSUE TITLE
Current conversions seem to be wrongly put in Conversions:Previous

### ISSUE THREAD

**Issue by SmartHypercube** [beancount/beancount#494]
```
2019-01-01 open Assets:A
2019-01-01 open Income:B

# In 2019, I got 1 USD

2019-02-01 *
  Assets:A  1.00 USD
  Income:B

# In 2020, I converted it to 7 CNY

2020-05-01 *
  Assets:A   7.00 CNY @
  Assets:A  -1.00 USD
```
Install `beancount==2.3.0` (latest release on PyPI). Use `bean-web` to open this file. Select "**year 2020**". You will see "Equity" table like this:

Account | Other
-- | --
Equity:Conversions:Previous | 1.00 USD<br>-7.00 CNY
Equity:Earnings:Previous | -1.00 USD
Opening-Balances |  

I earned 1 USD in 2019, and earned nothing in 2020. As I am viewing the year 2020, `Equity:Earnings:Previous` should contain -1 USD. `Equity:Earnings:Current` should be empty. They are both correct.

However, **I converted nothing in 2019, and converted 1 USD to 7 CNY in 2020. Why does `Equity:Conversions:Previous` show the conversion, while `Equity:Conversions:Current` is empty?** Is there a bug or I simply didn't understand what "current" and "previous" mean?

**Comment by blais** [comment]
This is indeed a bug, sending a fix. The unit test is correct, and the SQL query works fine as well, but the web invocation is the only one that calls clamp_opt() and that's incorrect.

```
bergamot [git|master]:~/p/beancount$ bean-query ~/r/q/beancount-data/user/hypercube/issue494.beancount  'print from open on 2020-01-01 close on 2021-01-01'
2019-01-01 open Assets:A
2019-01-01 open Income:B

2019-12-31 S "Opening balance for 'Assets:A' (Summarization)"
  Assets:A                  1.00 USD
  Equity:Opening-Balances  -1.00 USD

2019-12-31 S "Opening balance for 'Equity:Earnings:Previous' (Summarization)"
  Equity:Earnings:Previous  -1.00 USD
  Equity:Opening-Balances    1.00 USD

2020-05-01 * 
  Assets:A   7.00 CNY @ 0.1428571428571428571428571429 USD
  Assets:A  -1.00 USD                                     

2020-12-31 C "Conversion for (-1.00 USD, 7.00 CNY)"
  Equity:Conversions:Current  -7.00 CNY @ 0 NOTHING
  Equity:Conversions:Current   1.00 USD @ 0 NOTHING
```
