### ISSUE TITLE
docs are hard to reference and find

### ISSUE THREAD

**Issue by simonmichael** [beancount/beancount#503]
Excuse this complaint, it's intended to help. Beancount has arguably the best docs in plain text accounting, but they are always too hard to reference and find. Here are a few simple things that would help a lot:

- http://furius.ca/beancount/ -> Documentation section should include a link to the fast and navigable docs mirror at https://beancount.github.io/docs 

- https://beancount.github.io should have a front page or redirect linking there too, so that we can get to the docs by just remembering a hostname

- The "Health Care Expenses" doc at https://docs.google.com/document/d/16RKEl1NJ3qg8VU9vKRRvgIv3CyGs0_4ASS4lD5iBFTw/edit#heading=h.k8gf9rm4lopl, which I originally found via https://www.reddit.com/r/plaintextaccounting/comments/hl8vm0/healthcare_expenses_structuring and then had a hard time tracking down again, should be linked in the google and mkdocs docs. Even if it's unfinished, I've found it quite useful and inspiring.

Thanks for the docs!

**Comment by blais** [comment]
All great points indeed.

**Comment by blais** [comment]
I created beancount.github.io, a basic mirror of http://furius.ca/beancount.
furius.ca will go away at some point.

**Comment by blais** [comment]
I also updated the furius.ca/beancount site, which was out of date.

**Comment by blais** [comment]
Finally, added the incomplete doc to the index.

**Comment by simonmichael** [comment]
Wonderful, thanks Martin!

At https://beancount.github.io, the links are all rendering as literal blocks; better if they were clickable links.

**Comment by blais** [comment]
Will fix.

**Comment by dnicolodi** [comment]
A while back I submitted a PR to fix that.

**Comment by blais** [comment]
Fixed.
