### ISSUE TITLE
Input file encoding confusion

### ISSUE THREAD

**Issue by dnicolodi** [beancount/beancount#504]
The recent work on the parser and some still not merged work surfaced some inconsistencies in processing the Beancount input files regarding encoding. The ledger for the most part assumes UTF-8 encoding. The most relevant example is probably the definition of account names here https://github.com/beancount/beancount/blob/master/beancount/parser/lexer.l#L187. However, the parsing code allows to specify the encoding used to decode literal strings, used here https://github.com/beancount/beancount/blob/master/beancount/parser/lexer.l#L382. This code uses the `ignore` error handling policy is used (https://docs.python.org/3/library/codecs.html#error-handlers) and decoding errors are ignored.

There are unit tests that verify that passing an encoding to the parser does the right thing. However, there are inconsistencies in what is expected: passing a Latin1 encoded string when the default UTF-8 encoding is used is expected to yield a garbled string (https://github.com/beancount/beancount/blob/master/beancount/parser/lexer_test.py#L708), passing an UTF-16 encoded string in the same circumstances is expected to raise an exception (https://github.com/beancount/beancount/blob/master/beancount/parser/lexer_test.py#L735). Turns out that the exception is actually coming from somewhere else in the code and not from the string decoding.

I think string decoding errors should be reported. I don't think silently returning garbled strings is a good idea. In my opinion this is a bug fix and not a change in behavior.

I don't think that having string literals encoded in a different encoding than the rest of the input file is a sensible thing to do, and I don't know of a tool that would easily allow this. I think the code currently tries to support the case of encodings different from UTF-8 when account names are restricted to ASCII. This works when the given encoding encodes the ASCII subset to ASCII bytes values. This is a property of some "western" encoding systems like Latin1, but not universal. Incidentally, most (all?) Beancount tools do not allow to specify the input file encoding, thus the UTF-8 default is used. For those reasons I propose to remove the support for encodings different than UTF-8. @blais I may be missing something here. Do you remember why the possibility to specify a different encoding for just the string literals was introduced?

This may be seen as breaking backward compatibility (someone should have gone at long lengths to make non UTF-8 encoding work and I think we should have heard their screams, but I cannot exclude that some strange Beancount files exist in the wild). If this is a concert, I propose to keep accepting `encoding` parameter in the parsing functions but silently ignore it, and use the `replace` error handling policy for string literals but not for other strings. In this way the encoding problems should be evident.

The change should be a few lines patch to the code and an hundred lines patch to the tests.

**Comment by dnicolodi** [comment]
The `UnicodeDecodeError` raised when parsing an UTF-16 input file comes from the code that reports a syntax error from the lexer: here https://github.com/beancount/beancount/blob/master/beancount/parser/lexer.l#L455 the UTF-16 bytes that caused the error are copied into a C string, and here https://github.com/beancount/beancount/blob/master/beancount/parser/lexer.l#L531 we try to build a Python `str` object from them using UTF-8 encoding (the "s#" part of the argument format string, see https://docs.python.org/3/c-api/arg.html#c.Py_BuildValue).

Reporting the error like this is not generally safe as we don't know that the invalid data encountered is valid UTF-8. The simple fix is to do not report the input fragment that caused the error. The line number is already reported, and the column number could be easily added.

The alternative, more complex, fix is to report the error location as with non ASCII characters are escaped. This has the drawback that also UTF-8 characters will be escaped. In practice an error like `Invalid token: 'fü bar'` would become `Invalid token: 'f\xc3\xbc bar'`. Anothe solution could be to attempt to decode the string in UTF-8 but with a laxer error handling policy, like `backslashreplace` which would produce something like `Invalid token: 'fü\xff\xfeo bar'` (where I inserted a spurious UTF-16 character after the `ü`.

@blais Which solution do you prefer?

Note that this problem should in principle go away with RE/flex as it does, I believe, UTF-8 validation of the input, unlike Flex.

**Comment by blais** [comment]
Let's not waste any time changing this for v2. 
I don't want to break things in v2, v2 will become obsolete eventually.
This is a rabbit hole I don't have much time for...
v3 will use my RE/flex scanner and be 100% UTF-8.
