### ISSUE TITLE
Use on mobile?

### ISSUE THREAD

**Issue by delaaxe** [beancount/beancount#512]
I’m considering trying this out but I’d like to add transactions from my smartphone on the go.

Is there a recommended way to add entries from mobile? Does editing a note synced with iCloud work well enough in practice?

Just asking in case somebody’s already doing this.

**Comment by blais** [comment]
There's no dedicated app for Beancount.

This app works well:
https://play.google.com/store/apps/details?id=org.totschnig.myexpenses&hl=en_US

**Comment by xuhcc** [comment]
@delaaxe I'm using [Beancount Mobile](https://github.com/xuhcc/beancount-mobile/) to add transactions and [Syncthing](https://syncthing.net/) for syncing the beancount file between my devices. But it is available only on Android. Syncing file between devices works well in most cases, though one have to avoid editing it on two devices simultaneously.

**Comment by blais** [comment]
Ah yes! I forgot about this! I had even added it to the contrib doc. Sorry
Kirill.
