### ISSUE TITLE
Latest release does not compile on Windows (on AppVeyor at least).

### ISSUE THREAD

**Issue by yagebu** [beancount/beancount#522]
The CI build of Fava is currently broken due to the latest release of Beancount apparently not compiling on Windows (https://ci.appveyor.com/project/yagebu/fava/builds/34396347):

    beancount/parser/parser.c(336): error C2198: 'PyUnicode_FromString': too few arguments for call

Installing from git (branch v2) seems to fix it (https://ci.appveyor.com/project/yagebu/fava/builds/34397338). The line that throws the error is gated by an `#ifdef VC_CHANGESET` and maybe the passing of that compile option behaves differently on Windows.

**Comment by dnicolodi** [comment]
Passing the compilation flag to the compiler should work just fine, it is handled cross-platform by setuptools/distutils. The problem is that Windows does not have a decent C compiler and I don't have a Windows machine to test how broken it is. I'm surprised it works on the v2 branch, I'll have a look at it.

Is AppVeyor the state of the art for running CI on Windows? It may be worth to set it up for the beancount repo too, to avoid similar issues in the future.

**Comment by yagebu** [comment]
> I'm surprised it works on the v2 branch, I'll have a look at it.

It works because `VC_CHANGESET` is non-empty there. Passing of the empty compile option seems to behave differently.

> Is AppVeyor the state of the art for running CI on Windows? It may be worth to set it up for the beancount repo too, to avoid similar issues in the future.

Github actions also support Windows and might be a bit easier to setup. I'd also be in favor for adding a Windows build (although this issue exactly wouldn't have been caught by that).

**Comment by dnicolodi** [comment]
I haven't yet looked at what are the differences between the v2 branch and the latest release. I have been trying to get AppVeyor working going.

> Github actions also support Windows and might be a bit easier to setup. I'd also be in favor for adding a Windows build (although this issue exactly wouldn't have been caught by that).

Why this error would have not been caught?

**Comment by yagebu** [comment]
> I haven't yet looked at what are the differences between the v2 branch and the latest release.

There aren't any ;) This error happens only when not installing from git.
