### ISSUE TITLE
python-magic needs libmagic on Windows

### ISSUE THREAD

**Issue by dnicolodi** [beancount/beancount#523]
I am trying to run beancount tests on Windows on AppVeyor. They fail because python-magic has some problem loading libmagic:
```
platform win32 -- Python 3.6.8, pytest-5.4.2, py-1.9.0, pluggy-0.13.1
rootdir: C:\projects\beancount
collected 1617 items / 10 errors / 1607 selected
=================================== ERRORS ====================================
_______________ ERROR collecting beancount/ingest/cache_test.py _______________
beancount\ingest\cache_test.py:9: in <module>
    from beancount.ingest import cache
beancount\ingest\cache.py:14: in <module>
    from beancount.utils import file_type
beancount\utils\file_type.py:22: in <module>
    import magic
C:\Python36\lib\site-packages\magic.py:179: in <module>
    libmagic = ctypes.CDLL(dll)
C:\Python36\lib\ctypes\__init__.py:348: in __init__
    self._handle = _dlopen(self._name, mode)
E   OSError: [WinError 193] %1 is not a valid Win32 application
```

I tries getting libmagic from here https://github.com/nscaife/file-windows, but I get the same error...

@yagebu How do you run fava tests on AppVeyor?

**Comment by yagebu** [comment]
> How do you run fava tests on AppVeyor?

https://github.com/beancount/fava/blob/c3e1b67befd10f35a9279350bfaa5aeaab0314dd/appveyor.yml - due to a bug in python-magic, I've fixed the version of python-magic in `tox.ini`.

**Comment by dnicolodi** [comment]
It turned out that if I use `PYTHON: "C:\\Python38"` in appveyor.yml I get the above error, but not if I use `PYTHON: "C:\\Python38-x64"`... However, now I get a lot of test failures. I am investigating.

**Comment by yagebu** [comment]
I'd still consider this a bug that we should work around. A python lib with missing dependencies shouldn't crash Beancount if it's non-essential like python-magic. I'll open a PR with a work-around.

**Comment by dnicolodi** [comment]
I thought the error was caused by something wrong I did. Because of the different behavior in Python38 vs Python38-x64 I thought it had to do with trying to `dlopen()` (or whatever is the equivalent on Windows) a DLL compiled for a different architecture than the main process. However, you are suggesting this is not the case.
