### ISSUE TITLE
Github project description issue

### ISSUE THREAD

**Issue by pfalcon** [beancount/beancount#540]
Background: I'm a fan of both Python and personal finance management, looking forward to get to know any cool projects around. Beancount doesn't help people to get itself discovered.

The current description of https://github.com/beancount/beancount (right near-top corner) is "Official Beancount repository." This is what people get in search, etc., and likely pass by. It's only if one scrolls down to the README, one can read "beancount: Double-Entry Accounting from Text Files". Well, **that** should be the project description, to let anyone discover what it is at once. Thanks.

**Comment by blais** [comment]
Thanks Paul.
