### ISSUE TITLE
Adopt pipenv/poetry to make build reproducible 

### ISSUE THREAD

**Issue by yegle** [beancount/beancount#542]
Hi,

Is there a plan to adopt pipenv/poetry to make the build process reproducible? Or is this a solved problem once v3 uses Bazel?

**Comment by blais** [comment]
No plan.
Bazel is pretty hermetic, and the way I have it setup it depends only on 
- Your compiler (which should be clang)
- The local Python installation
It downloads all the rest, even builds its own flex/bison/RE2, etc.

I have no idea what this means for MS Windows.
