### ISSUE TITLE
extract a dict importer to table importer fronm CSV.importer

### ISSUE THREAD

**Issue by trim21** [beancount/beancount#546]
This could also help user to support HTML table or excel.

**Comment by dnicolodi** [comment]
The importers in the beancount codebase are mostly meant to be examples, not a complete framework to write importers. Having the flexibility to cover everyone needs would make them as complex as writing your own code. CSV is a sufficiently common format that a shared importer saves some coding in the most common cases, however, covering all possible quirks and extensions is outside its scope.

Writing an importer from tabular data is extremely easy: just iterate the rows and instantiate `Transaction` objects. It can be done in less than 10 lines of code. The code needed to obtain tabular data from HTML or Excel is going to be significantly longer than that. I would suggest you to write these importers from scratch. If you think that some utility functions may make writing these importers easier, we may look into adding them instead.

**Comment by blais** [comment]
I agree with Daniele. In fact, in v3 I'd like to move the CSV importer to its own repo, it was really intended to be just an example (but it works too well, so it has grown without enough tests).
