### ISSUE TITLE
Release version 2.3.2

### ISSUE THREAD

**Issue by dnicolodi** [beancount/beancount#548]
I suggest to release version 2.3.2 after #535 is merged. I would have liked to release 2.3.2 with all the parser cleanups I am working on, but the issue preventing compilation on Windows affects more users that I expected. 2.3.1 supposedly fixes some bugs in the handling of non-ascii filenames on Windows, for example #547. It is a pity these fixes cannot readily reach Windows users. Also, we have now infrastructure in place to release binaries on PyPI, making installing on Windows much easier. It would be a nice occasion to test it.

**Comment by blais** [comment]
Will do.

**Comment by blais** [comment]
released
