### ISSUE TITLE
docs: add a new plugin beancount_share

### ISSUE THREAD

**Issue by Akuukis** [beancount/beancount#587]
Please add my beancount [plugin `beancount_share`](https://github.com/Akuukis/beancount_share) to [Beancount - Contributions](https://docs.google.com/document/d/1Z37bQ45wDtjTPaMQ_x-f33p1trH9fNosEAUgbQXwp30/edit#heading=h.pmdvjaaz2xcr).

It is inspired by your snippet at our [previous conversation](https://github.com/beancount/beancount/issues/474) about partial expense diverts within one ledger based on ["How We Share Expenses"](https://docs.google.com/document/d/1MjSpGoJVdgyg8rhKD9otSKo4iSD2VkSYELMWDBbsBiU/edit) cookbook. This plugin is generic enough for public use, and can cover the usecases described in the cookbook (see [tests](https://github.com/Akuukis/beancount_share/blob/master/tests/features/usecases.feature#L27-L76)).

I hope you find this plugin good enough to mention it in cookbook too, instead of current comment "exporting this externally is TBD, [..]". Let me know if it works for you!

**Comment by blais** [comment]
Done, added. Thank you.
