### ISSUE TITLE
Recording future liabilities.

### ISSUE THREAD

**Issue by jahagirdar** [beancount/beancount#590]
At end of financial year, I need to record liabilities that will be incurred for auditing the account. The actual audit and related payments take place a few months down the line,
Right now I am doing this through an intermediate "futureExpenses" and "futureLiabilities" account. Transfering money from futureExpenses to futureLiabilities at year end. and Bank to futureExpenses at the date when the payment is made.

Is it possible to record this as a single transaction instead of two separate transactions?

**Comment by blais** [comment]
To your specific answer: Yes, you can always combine transactions.

But the account names you're posting to/from seem unusual. Assets:AccountsReceivable and Liabilities:AccountsPayable are the common pending transfer accounts people use. If you can insert an example transaction here that would help.

**Comment by jahagirdar** [comment]
Here are two related transactions
In India the financial year begins in April.
Hence at the end of March I am recording a future liability towards Auditors fees.
```
2019-03-31 * "Auditors fees"
        Expenses:INR:Auditor 10000 INR
        Liabilities:INR:AccountPayable
```

The Audit process finished a few months later and the auditor encashed the check. Hence recording the settlement in Oct.
```
2019-10-29 * "Auditor Fees"
        Liabilities:INR:AccountPayable 10000 INR
        Assets:INR:Bank:Current
```

I was wondering whether this can be recorded as a single transaction like
```
2019-03-31 * "Auditors fees"
        Expenses:INR:Auditor 10000 INR
        Assets:INR:Bank:Current settled: "2019-10-29"
```

**Comment by blais** [comment]
This will be possible in v3, but the feature will be targeted to deal with the small (only a few days) difference between transaction posting date and settlement. It would automatically be split in two and post to a "transfer" account. For the use case you have, I would still recommend using a proper A/P account.
