### ISSUE TITLE
Documents from a directory Option does not work as expected from an include

### ISSUE THREAD

**Issue by samjcarter** [beancount/beancount#596]
### Description of Issue

Using a documents option to generate document journal entries from a directory, as in [https://beancount.github.io/docs/beancount_language_syntax.html#documents-from-a-directory ](https://beancount.github.io/docs/beancount_language_syntax.html#documents-from-a-directory) works if the option is **not** written in a file that is an include to your main file. It does work when written directly in to your main file.

### Software versions used for testing

- beancount==2.3.3
- fava==1.17

Other software used:

- Visual Studio Code 1.52.1
- Firefox 84.0.1 (64-bit)
- Ubuntu 20.10

### Steps to reproduce

1. Set up a new beancount project in a new directory with a fresh python virtual environment `python -m venv .venv` 
2. activate virtual environment `source .venv/bin/activate`
3. install beancount and fava `pip install beancount fava`
4. create a new empty beancount file `touch main.bean`
5. in `main.bean` add an option to a docs directory `option "documents" "docs"`
6. create that directory. `mkdir docs`
7. in main.bean add an account. `2020-12-26 open Assets:Bank`
8. create a hierarchy of directories mirroring the bank account. `mkdir docs/Assets` and `mkdir docs/Assets/Bank`
9. place a correctly named document inside the bank directory `docs/Assets/Bank/2020-12-27_filename.pdf` or similar.
10. open the Beancount file in Fava `fava main.bean` and go to the documents or journal link, and you should see the automatically created entry for that document.
11. **Now "Break it"**
12. create a new beancount file called `options.bean`
13. cut the `option "documents" "docs"` line out of `main.bean` and paste it into `options.bean`.
14. add an include to the first line of  `main.bean`:  `include "options.bean"` 
15. now refresh or re-open `main.bean` in fava and the document placed in `"docs"` disappears.
16. reverse the steps after "**Break it**" by commenting out the `include` and putting the `option "documents" "docs"` line back into the `main.bean` file. Check that the documents re-appear in Fava or `bean-report main.bean journal`

**Comment by dnicolodi** [comment]
In the current implementation, the `include` directive is not to be intended as a literal inclusion of the content of the included file in the source file (like the C pre-processor `#include`) but as a way to merge the interpreted content of the files. This results in the surprising behavior reported here and other limitations. I think there is agreement that the `include` directive should be revisited to be a literal copy in place of the included file. This will likely be implemented in v3.

**Comment by samjcarter** [comment]
Hi Daniel, thank you for the clarification.

Just to state again for anyone else reading this, You can move the `Documents` option to the main file, where the includes are, and it should work as you'd expect.
