### ISSUE TITLE
"Calculating Portfolio Returns" scripts doesn't exist

### ISSUE THREAD

**Issue by lama-pacos** [beancount/beancount#601]
The source code can be found here.

https://github.com/beancount/beancount/blob/v2/experiments/returns/compute_returns.py

the link is not found

**Comment by dnicolodi** [comment]
I don't understand what this issue is about. Where did you find that link?

The `experiment` folder in the source distribution of Beancount has been moved to its own repository https://github.com/beancount/beanlabs and the script you mention is here https://github.com/beancount/beanlabs/blob/master/beanlabs/returns/compute_returns.py

**Comment by blais** [comment]
My doc hasn't been updated, probably

**Comment by blais** [comment]
I changed the main link. Have to run uptown for a few hours.
(I desperately need a script against the GoogleDocs API that will allow me rewriting links...)

**Comment by blais** [comment]
Served by way of code
https://github.com/beancount/beancount/commit/4423b9850854175528d829ca01790b324c7d57c1

**Comment by SamuelQZQ** [comment]
@blais @dnicolodi Sorry for disturbing. It seems the `compute_returns.py` has been moved to somewhere else again. Do you know where can I find it?

**Comment by blais** [comment]
Look for beangrow

**Comment by michaelMinar** [comment]
Sorry for restarting this thread, but I was so excited about the granular calculations involved here when I read https://beancount.github.io/docs/calculating_portolio_returns.html.

However, I'm not able to find reference to the returns script or beangrow in the docs or code. Do you have a pointer or example of it in action?

**Comment by michaelMinar** [comment]
I see that it is in a separate repo, my apologies for restarting this thread.
