### ISSUE TITLE
Test: doesn't work with non-standard python path

### ISSUE THREAD

**Issue by tecosaur** [beancount/beancount#607]
Oh some distros / build-servers, the python path is non-standard.

Quite frankly I have no idea about this, maybe @dcermak might be able to help.

https://github.com/beancount/beancount/blob/a576ae368aff3b6eec3420a01b785b97dc45490c/beancount/scripts/setup_test.py#L33-L44

**Comment by dcermak** [comment]
The code should not manually try to construct the site-packages directory as that will obviously fail for non-standard installations. Instead I would recommend to resort to one of the options from: https://stackoverflow.com/a/46071447

**Comment by dnicolodi** [comment]
Can you please provide the traceback for the case in which this fails? In which environment does this fail?

**Comment by dnicolodi** [comment]
Quite frankly ripping out these tests and replacing them with something more robust has been on my todo list for quite some time. Maybe it is time to bump this item up in the list...

**Comment by blais** [comment]
Actually these tests have saved me a bunch of trouble in the past. Making sure the basic distutils setup succeeds is a good baseline. Not sure I'd want to do away from them. v3 will require something brand new, but of equivalent functionality.

**Comment by dnicolodi** [comment]
The idea is to implement these tests in another way, not to remove them.
