### ISSUE TITLE
Cannot add transaction with missing currency in plugin

### ISSUE THREAD

**Issue by ksesong** [beancount/beancount#609]
I am trying to make a plugin that creates directives based on some external files. These files may change over time, and so the resulting directives will change as well (some may be removed, others may be added), see it as a 1-way synchronization.

The main ledger test file is basic:
```beancount
option "operating_currency" "EUR"

plugin "plugin-test"
```

The plugin itself has been simplified to highlight the issue:
```python3
from beancount.parser import parser

__plugins__ = ['run']


def run(entries, options_map):
    return (
        entries
        + [
            parser.parse_one("2020-01-15 open Expenses:Test"),
            parser.parse_one("2020-01-15 open Assets:Account"),
            parser.parse_one(
                """
2020-01-15 * "" "Test"
  Expenses:Test 100 EUR
  Assets:Account
"""
            ),
        ],
        [],
    )
```

When running `bean-check`, the following error appears: 
```
AttributeError: type object 'MISSING' has no attribute 'currency'
```
If I were to copy these different directives onto the main ledger manually, there would be no error.

**Comment by blais** [comment]
That's not going to work. Plugins expect finalized (interpolate & booked) transactions (not merely parsed) without any missing numbers or currencies and are expected to output as such as well.  Just add -100 EUR explicitly on the second posting and don't rely on interpolation.

(BTW This will be well defined in v3, along with the capability to invoke booking explicitly per transaction and a better plugin system.)
