### ISSUE TITLE
Allow reopening an account ?

### ISSUE THREAD

**Issue by alarsyo** [beancount/beancount#611]
For quick debts with friends, I'd like to just dynamically open and close debt accounts in my ledger, like so:

```
2021-01-15 open Liabilities:Dette:Firstname-Lastname

2021-01-15 * "Firstname bought me lunch"
  Liabilities:Dette:Firstname-Lastname    -8.00 EUR
  Expenses:Food

2021-01-15 * "Firstname Lastname" "Reimbursement for lunch"
  Assets:Checking                         -8.00 EUR
  Liabilities:Dette:Firstname-Lastname

2021-01-16 balance Liabilities:Dette:Firstname-Lastname 0.00 EUR

2021-01-16 close Liabilities:Dette:Firstname-Lastname
```

Unfortunately that only works the first time, if I have a second debt with the same person then I can't reopen that account, I get a `Duplicate open directive for...` error.

[Relevant code here](https://github.com/beancount/beancount/blob/41f0d5209f92962fe8857ff3813b74fb413615e6/beancount/ops/validation.py#L70-L78)

Is this really a behavior you want ? I can definitely think of situations where reopening a previously closed account makes sense (the simplest one being, you change banks, then come back to your previous bank, for whatever reason).

It definitely makes the implementation of the validation a bit more complex though, but from what I can see the code linked above already assumes that the list of entries is sorted chronologically (otherwise validating `close` directives would need to process all `open` directives first).

**Comment by blais** [comment]
Just keep the account open.
I see no need to support this, the close directive is not only used to check for transaction during the period, but also for other things (figuring out the list of accounts). A single open/close is sufficient IMO

**Comment by alarsyo** [comment]
> I can definitely think of situations where reopening a previously closed account makes sense (the simplest one being, you change banks, then come back to your previous bank, for whatever reason).

So what would be the solution for opening a checking account in a bank where you closed one, like, 10 years ago ? Or even better, an `Income:Employer` account for an employer who you worked for, then left, then came back to ? Just remove the previous `close` directive ?

> Just keep the account open.

This isn't a great solution, as an unclosed account will show up on reports and fava. I don't want to see all the friends I've had debts with in 10 years of history. Hence why I wanted to close these once the debt is gone :sweat_smile:

**Comment by pfrancois** [comment]
if you close a account in a bank then reopen one, it is not the same. so better to have two account in beancount...

**Comment by blais** [comment]
That's right. Just use another account name.
