### ISSUE TITLE
beancount.utils.misc_utils.log_time doesn't append newline at the end.

### ISSUE THREAD

**Issue by emowen4** [beancount/beancount#618]
Here is the link to the log_time function. Is it on purpose that not appending \n here?

https://github.com/beancount/beancount/blob/master/beancount/utils/misc_utils.py#L50

```python3
def log_time(operation_name, log_timings, indent=0):
    time1 = time()
    yield time1
    time2 = time()
    if log_timings:
        log_timings("Operation: {:48} Time: {}{:6.0f} ms".format(
            "'{}'".format(operation_name), '      '*indent, (time2 - time1) * 1000))
```

**Comment by blais** [comment]
Yes, if you're using logging.info, for example

**Comment by emowen4** [comment]
Thanks for your reply!

If I understand correctly, when I pass sys.stdout to loader.load_file as log_timing param, all timing logs are in single line in console is the correct behavior?

**Comment by blais** [comment]
https://github.com/beancount/beancount/commit/9793d10876bbf186b3b120562629feeee122e3f2
