### ISSUE TITLE
Installation link dead

### ISSUE THREAD

**Issue by radnonymous** [beancount/beancount#622]
The link for installation instructions (http://furius.ca/beancount/doc/install) cannot be reached.

**Comment by dnicolodi** [comment]
The documentation is here: https://beancount.github.io/docs/, in particular: https://beancount.github.io/docs/installing_beancount.html

**Comment by blais** [comment]
The server is back up.
I need to migrate all these redirects through github at some point

**Comment by gawin** [comment]
@blais http://furius.ca seems to be down again?
_(also couple of days ago when I checked)_
