### ISSUE TITLE
Beancount project donations?

### ISSUE THREAD

**Issue by mtlynch** [beancount/beancount#627]
Does this project accept donations?

If you want to offer a way for users to support the project financially, you can add a file called [`.github/FUNDING.yml`](https://docs.github.com/en/github/administering-a-repository/displaying-a-sponsor-button-in-your-repository#about-funding-files).

It can be as simple as a PayPal address like:

```yaml
custom: https://paypal.me/your-paypal-address-here
```

**Comment by blais** [comment]
Hi Michael!
Thank you for this suggestion.

I've been thinking about it for a long while, given the enormous amount of free time I've put into this, but at the same time, I've wanted to keep independence and not feel swayed to implement things for particulars, so I never added it. I probably should do it and segregate the donation funds to spend on Beancount related material or events. I'll add it.

Maybe I should cather to the BTC "nouveau riche" folks and promise in return to add features for crypto ;-)

**Comment by blais** [comment]
Thanks a lot Michael! Really appreciated.
