### ISSUE TITLE
 Build of v2.3.3 fails because of google-auth dependency

### ISSUE THREAD

**Issue by codedump** [beancount/beancount#634]
Hello,

I'm trying to build `beancount` v2 from source. I have a `Dockerfile` that's built before, but now it fails. The relevant part of the build log I think is this:

```
Searching for google-auth>=1.16.0
Reading https://pypi.org/simple/google-auth/
Downloading https://files.pythonhosted.org/packages/68/c3/6851ad3e029ac11e4beb6470b9465f4affce345cba8ef7cbf7fbd647c89a/google_auth-2.0.0.dev0-py2.py3-none-any.whl#sha256=50eda7bbeaed36ad17a87a94a770b9ec97e9a64add701942a4cd4dcbe291f3df 
Best match: google-auth 2.0.0.dev0
Processing google_auth-2.0.0.dev0-py2.py3-none-any.whl
Installing google_auth-2.0.0.dev0-py2.py3-none-any.whl to /usr/local/lib64/python3.9/site-packages
Adding google-auth 2.0.0.dev0 to easy-install.pth file
...
Installed /usr/local/lib64/python3.9/site-packages/googleapis_common_protos-1.53.0-py3.9.eg
error: google-auth 2.0.0.dev0 is installed but google-auth<2.0dev,>=1.21.1 is required by {'google-api-core'}
Error: error building at STEP "RUN cd /opt..."
```

The first part tells me that the installer wants google-auth>=1.16.0, and finds 2.0.0.dev0, and thinks it's good.

The 2nd part tells me that it tries to build google-common-protos, but chokes on the too recent google-auth version. I'm not sure if this is a bug in Beancount or in a Google API package.

The last line is (the beginning of) the `podman` error message, you can safely ignore that. I'm just including it for reference.

The `Dockerfile` I'm using is [this](https://gitlab.com/codedump2/fin-tools/-/blob/master/Dockerfile), the relevant build script is:
```
cd /opt
git clone --recurse-submodule https://github.com/beancount/beancount beancount-v2
cd beancount-v2
git checkout 2.3.3
git submodule update
python3 setup.py install
```

I'm aware that the submodule part is probably not needed, but shouldn't hurt. I successfully built an image about 2 months ago with a similar script:
```
git clone --recurse-submodule https://github.com/beancount/beancount beancount-v2
cd beancount-v2
git checkout v2
...
```

The reason I made the change in `checkout` from `v2` to `2.3.3` is because I hoped that the build issue would be an issue of the HEAD of the v2 branch, but apparently isn't. It looks to me as if one of the dependency specification(s) for `google-auth` was sloppy, it didn't account for the package version to ever changing above v1 at a specific location (while downloading), but specifically *excluded* v2 at another location.

I'm not proficient enough with Python build systems to fix this, but maybe someone can? :-)

Cheers,
F.

PS: Oh, and BTW, thanks for writing Beancount, awesome piece of work :-)

**Comment by dnicolodi** [comment]
This is not an issue in the Beancount build system:
```
$ mkdir beancount2.3
$ cd beancount2.3/
$ python -m venv .
$ bin/python -m pip install git+https://github.com/beancount/beancount.git@v2
...
$ bin/python -m pip freeze
attrs==20.3.0
beancount==2.3.3
beautifulsoup4==4.9.3
bottle==0.12.19
cachetools==4.2.1
certifi==2020.12.5
chardet==4.0.0
google-api-core==1.26.0
google-api-python-client==1.12.8
google-auth==1.27.0
google-auth-httplib2==0.0.4
googleapis-common-protos==1.53.0
httplib2==0.19.0
idna==2.10
iniconfig==1.1.1
lxml==4.6.2
packaging==20.9
pluggy==0.13.1
ply==3.11
protobuf==3.15.3
py==1.10.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pyparsing==2.4.7
pytest==6.2.2
python-dateutil==2.8.1
python-magic==0.4.22
pytz==2021.1
requests==2.25.1
rsa==4.7.2
six==1.15.0
soupsieve==2.2
toml==0.10.2
uritemplate==3.0.1
urllib3==1.26.3
```

It seems that your python environment comes with packages with versions or requirements contradicting Beancount requirements. The pip output snippet you provide is not enough to diagnose where the versions diverge. In general, mixing platform packages with pip installed packages is not a good idea and the uyse of virtual environment is recommended. I don't know Alpine Linux or Docker enough to investigate this further. Note that Beancount v2 `setup.py` has not changed in quite a long time thus if this broke recently the change is probably in your environment.

**Comment by codedump** [comment]
Thanks for the swift reply!

> In general, mixing platform packages with pip installed packages is not a good idea and the uyse of virtual environment is recommended. I don't know Alpine Linux or Docker enough to investigate this further.

As far as environment separation from the host is concerned, you can think of a container as of a virtual machine. In this case, the "virtual machine" is running a standard Fedora installation (I'm using Fedora as the basis for the Docker container, not Apline), which is pimped up by the scripts like the one I just posted.

But you were right, apparently it was one of the system packages conflicting with a pip package that I brought in (pyledger). I removed the pyledger installation and now it works. I'm closing this if that's ok with you.

Thanks & sorry for the hassle!

**Comment by dnicolodi** [comment]
Containers (in their most commonly used form) use full blown operative systems as payloads: there is nothing there that protects you from package versions mismatch when you install different applications via pip in the same installation, as you experienced. 

I don't really see the point in using a container provisioned with a full blown Fedora installation for the sake of isolating a python application that does not have dependencies that go beyond what can be easily installed in a Python virtual environment. But I also don't share any of the excitement for Docker that is so common out there. I must be missing something...

**Comment by blais** [comment]
just comment out the dependency for your environment it's just for a tool
to upload to google docs

Daniele: Docker really cool for cloud deployments or servers or isolating
from changes. I run furius.ca from a container. Check it out.

**Comment by dnicolodi** [comment]
I use containers too, just not Docker containers, and not for running "desktop" applications.

**Comment by codedump** [comment]
@dnicolodi For the sake of completeness, I'd like to make a distinction here (not necessarily for you, since you know containers, but for other lurkers and Google Search guests):
  - **Containers as a concept**:  that's essentially Linux namespacing (think: `chroot` on steroids, basically extended to also include networking and storage, not only processes). It's all inside the Linux kernel and all containers are based on that.
  - **Containers as a format**: specifications of how to save the "`chroot` images". I guess one could essentially go with a .ZIP file or something. But the "Docker format" is nowadays standardized as the official OCI (Open Container Initiative) image format, and staying with that allows one to use standard tooling for management.
  - **Container tooling**: "Docker" is a typical tool (the first), but is an overblown beast these days. One could also use a few lines of home-grown Bash -- as I said, the Linux kernel has it all included. But I personally use Podman, which is pretty lightweight, while being Docker CLI compatible (this makes using external tooling a lot more easy than going for lx containers or something else.)

As far as "container tech" goes, I was very late to the "party", only starting seriously using it about 1 years ago. But I'm pretty much sold. If you avoid giant tooling (Docker), they're good use for the right reasons. I personally use them for separation -- on servers, arguments are trivial. But also on the desktop I wouldn't miss them -- I've grown into liking them after using Fedora Silverblue as a Linux distro for a while (which is essentially is an immutable base OS, with everything else being a container of one type or another).

With regards to financing, Ledger, and in particular other tooling like AquaBanking (HBCI interfacing software), I've had several episodes of "need to do accounting now" and "Oh $^&@%t, I've `dist-upgrade`-d my system 2 weeks ago and my tools bumped versions, I need to fix all my scripts". This is because some tools are particularly sensitive, but also because I'm changing computers pretty often -- between Laptop, Desktop and Work Laptop I have 2-3 instances of my work data at any given moment. Having started with Beancount 2 months ago, I wanted to avoid this happening again.

(I should also mention that I keep all my private data in two dozen or so git-repos, which is how I sync, and how I backup stuff -- been doing this for ~10-ish years. Everything that's not a git repo in my home folder is disposable.)

So moving from computer to computer with a tool as essential as Beancount, and as sensitive to versioning as AquaBanking, just gives me shivers. Containers fix that for me, even -- and in particular -- for regular "desktop" usage :-) As an added benefit, I can version-control the Dockerfile together will all other scripts (import scripts etc). This gives me instant reproducibility of my work environment at the cost of saving / versioning a single text file. So I have a _lot_ less work to do when moving between computers / installations / distros / versions. (Here I'd like to throw in that I love how the preferred way of storing documents in Beancount is together with the ledger data, and how Fava automagically integrates that -- I was sold the moment I read the (comprehensive) documentation :+1: :-)

As to the "full blown distro" -- it's not as bad as it sounds. Any basic distro is essentially 100 MB or so (basic stuff, think `debootstrap` if you will), and for any specialized activity (like financing), I typically make one or more dedicated container that I don't share with anything else. So whether it's `pip` or `apt` or `dnf` -- as long as it works and delivers the tool versions I need, I'm using it. I don't worry anymore about not "polluting" my system with different packaging systems.

I pinch my fingers occasionally, when I'm too far out of my depth (e.g. Python packaging), but most of the time the solution is pretty straight-forward (like in this case -- thanks again!). It's also less problematic than maintaining a clean "classic" distro install (Debian, Fedora, etc...) by forcefully staying within the "official" package management paradigm.

Now I have two git repos --  a `fin-tools` repo which I already linked to, and a `fin-data` repo which is my beancount ledger with PDF documents, bank statements, online-banking secrets, sensitive config files etc. Starting to do bean counting work :) on any freshly installed computer is a matter of 60 seconds to me. Syncing between computers is a no-brainer, just `push`/`pull` on the `fin-data` repo.
