### ISSUE TITLE
Settlement Date

### ISSUE THREAD

**Issue by jvasile** [beancount/beancount#640]
I frequently have the task of reconciling a beancount file against a set of transactions exported from my bank.  I've written some scripts to help identify discrepancies, and they operate by trying to match daily balances between my account and my beancount ledger.

I have found that the bulk of the mismatch (other than actual mistakes in my record-keeping) is that the transaction date and the settlement date don't line up.  I buy a piece of equipment with a debit card, but the charge doesn't appear for a few days.  I deposit a check, and it hits my account 24 hours later.  I pay a contractor by check, and she doesn't cash the check for a month.

In these cases, I end up changing the beancount entry's date to match the date the transaction hits the bank.  That's fine, but it removes a piece of information, which is the actual date I made payment.  Usually this doesn't matter.  But sometimes it does, and I'm left without much recourse in the files except to start adding comments with that data, which feels suboptimal.

I saw that this issue is raised in https://beancount.github.io/docs/settlement_dates_in_beancount.html and I'm wondering about current status of that discussion.  I quite like the "=settlement date" notation (ledger used it too) and the "S" prefix on a posting seems like a neat data entry solution.

Thank you!

**Comment by blais** [comment]
That's something I'm planning to address for the next major revision:
https://docs.google.com/document/d/1qPdNXaz5zuDQ8M9uoZFyyFis7hA0G55BEfhWhrVBsfc/edit#heading=h.dzmtky2u5kj8

It's moving slowly though, there's a ton of work TBD

**Comment by jvasile** [comment]
I see that.  Thank you.  I look forward to seeing that work move forward, and I'm happy to see if there are any places to pitch in.
