### ISSUE TITLE
Is there a get_balance function in beancount?

### ISSUE THREAD

**Issue by xfer44** [beancount/beancount#641]
Hi,

Sorry for this very basic question.
I looked around (ops/balance.py, core/account.py, or core/data.py) but I'm not able to find it in the source code or the documentation.

Is there a function to get the balance of an account? Ideally, something like this pseudocode:

```
from beancount import loader
entries, errors, options_map = loader.load_file("beancount file")
balance_amount = get_balance("account_name", entries)
```

Thanks

**Comment by blais** [comment]
There aren't any that specific, but you can compute the balances for all
the accounts once and pull the balance for your particular account.
Two ways to do that right now (which will get consolidated into one in v3):
1. beancount.ops.summarize.balance_by_account()
2. beancount.core.realization.realize()

**Comment by xfer44** [comment]
Thank you
