### ISSUE TITLE
Move `upload-to-sheets` somewhere else and slim down dependencies

### ISSUE THREAD

**Issue by dnicolodi** [beancount/beancount#654]
With bits and pieces splitting off the main beancount repository and package, it would be nice to move `upload-to-sheets` somewhere else (beanlabs?). I don't think this tool belongs with the rest of the beancount and removing it would allow to slim down considerably the (transitive) dependencies.

With `upload-to-sheets` gone, the only dependencies would be `python-dateutil` (which we can consider ditching once we can switch to the timezone handling in recent Python releases), `ply` (which also goes away once we promote the `beanquery` package as official source for the `bean-query` utility), `pytest` (that can be reduced to an optional dependency to run the test, although this requires adjusting some code that depends on it), and `click` (which does not have dependencies outside the standard library). In contrast the `google-api-python-client` required by `upload-to-sheets` brings in a couple of dozen packages.

**Comment by blais** [comment]
I like the idea, give me the weekend to find a new home.

**Comment by blais** [comment]
Note that I put it there on purpose, that is, it's a tool used in importing, a lot, but I think the deps argument is stronger.

**Comment by blais** [comment]
Oh wait, it's still in beancount. I meant to move this to beangulp

**Comment by blais** [comment]
Moved.
