### ISSUE TITLE
many of doc links are broker in importing_external_data

### ISSUE THREAD

**Issue by broven** [beancount/beancount#663]
like 
- [writing an importer](https://beancount.github.io/docs/importing_external_data.html#writing-an-importer) section importer.py
- [[Importing External Data - Beancount Documentation](https://beancount.github.io/docs/importing_external_data.html#writing-an-importer)] beancount.ingest.regression

I want help fix this, so I search in master, can`t find information about importer.py

**Comment by dnicolodi** [comment]
The importers framework has been branched out in its own project for the upcoming Beancount v3 release, thus it is no more in the repository `master` branch, but it persists in the `v2` branch. Just replace `v2` for `master` in the URLs.
