### ISSUE TITLE
option long_string_maxlines doesn't work

### ISSUE THREAD

**Issue by jaki** [beancount/beancount#675]
Option "long_string_maxlines" does not work these days because the default value 64 is hardcoded into compiled code (`tokens.c`):

```c
#define LONG_STRING_LINES_MAX 64
```

Some artifacts for the option remain, like `def get_long_string_maxlines` in `grammar.py`.  Either get rid of the artifacts and mark the option deprecated, or fix it.  I do not think it is feasible to provide the option in the same way since it affects the lexing/parsing in the middle of lexing/parsing.  Ideally, this is an option that can be set after compilation so that users don't need to compile with edited source code.

One alternative is to add another type of token "docstring" that don't have a line length limit, but this may add too much complexity to the lexer/parser.

Please post other ideas if you have any.

**Comment by dnicolodi** [comment]
Indeed the option has no effect after the recent rework of the parsing code and I forgot to adjust the options implementation accordingly. The check for the maximum number of lines in a string is an attempt at returning hopefully more useful errors when closing quotes are missing, although I don't know how effective it is in practice, as quotes appear often enough in the ledger to make triggering the check quite unlikely. Emitting a deprecation warning when the option is encountered is a good idea. I'll prepare a patch.

Do you have an use case for string containing more than 64 lines?

I think the test could be actually dropped as I don't think it is easy to trigger in common situations when closing quotes are forgotten. I can try to test this and get a better understanding.

**Comment by jaki** [comment]
Yes, for a plugin, it looks neater if I supply a string with many lines.  If the 64 limit can be dropped entirely, that works for me.

**Comment by jaki** [comment]
I found I can split it up to multiple plugin directives, so this isn't a big issue for me anymore.  It should still be marked deprecated.  A fix to support it is still a nice to have since splitting it up is a bit hacky and not all plugins support multiple occurrences.

**Comment by dnicolodi** [comment]
Which plugin requires a configuration that takes more than 64 lines? Editing that in a string within a Beancount ledger is not fun and would probably be better in a dedicated file. Anyhow, I would like @blais opinion about dropping the string line limit.

**Comment by dnicolodi** [comment]
Beancount v3 uses a string length limit of 16 kb which is much more than 64 lines, on average. I would argue that such an high limit is less useful than the 64 lines current one as it is very very unlikely that a Beancount ledger exists where no `"` appears in 16 kb. I am for dropping the limit all together.

**Comment by jaki** [comment]
@dnicolodi, the zerosum plugin, which is not part of this repo.  [I heard beancount v3 might make the plugin unnecessary.](https://github.com/redstreet/beancount_reds_plugins/pull/16#issuecomment-773882610)

**Comment by dnicolodi** [comment]
The lines limit in strings has been removed.
