### ISSUE TITLE
Idea: SHA1 hash for linking transactions

### ISSUE THREAD

**Issue by nils-werner** [beancount/beancount#682]
I just came across a situation in which I would like to add an "unimportant link" between two transactions. Unimportant means I would like to link them, but don't necessarily want to create a `^handle` for them.

```
2021-10-13 * "Coffee"
  Assets:Creditcard                           -53.80 EUR
  Expenses:Food:Coffee

2021-10-13 * "Coffee Reimbursement"
  Assets:AccountsReceivable                   -53.80 EUR
  Expenses:Food:Coffee
```

This made me think that maybe it would be nice if beancount could create transaction link handles from the SHA1 sum of some key values of the transaction, i.e.

```
SHA256("2021-10-13 Coffee") = ffbebdc01b5df28551aba6532bb2a22eb53133e225e3eca22693450275e8ae0e
```

So that I can link them using the truncated hash

```
2021-10-13 * "Coffee"
  Assets:Creditcard                           -53.80 EUR
  Expenses:Food:Coffee

2021-10-13 * "Coffee Reimbursement" ^ffbebdc
  Assets:AccountsReceivable                   -53.80 EUR
  Expenses:Food:Coffee
```

I haven't thought about the UI, e.g. where you would get the hash of the transaction in question. But disregarding that, could this be an interesting idea?

**Comment by blais** [comment]
It's going to be pretty opaque what is linked to what...
Why not create a tool in Emacs that inserts the links?
Or some common metadata?

Also, what's the concern with a distinction of important vs. unimportant? Links aren't that special. They were designed for the type of use case you mention.

Finally, you could create a plugin that *programmatically* inserts those links; they're not in the input file, but they would appear in any output automatically.  Should be a very easy plugin to write.

**Comment by dnicolodi** [comment]
I agree completely with what Martin says. The following implements the Emacs tool that Martin suggested.

```elisp
(defun beancount--bounds-of-transaction-at-point ()
  (save-excursion
    (cons (beancount-goto-transaction-begin) (beancount-goto-transaction-end))))

(defun beancount--transaction-sha1 ()
  (let ((bounds (beancount--bounds-of-transaction-at-point)))
  (secure-hash 'sha1 (current-buffer) (car bounds) (cdr bounds))))
  
(defun beancount-insert-sha1-link ()
  (interactive)
  (let ((link (format "^%s" (substring (beancount--transaction-sha1) 0 10))))
    (kill-new link)
    (save-excursion
      (beancount-goto-transaction-begin)
      (forward-line)
      (insert "  " link)
      (newline))))
```

The `beancount-insert-sha1-link` inserts a link in the transaction at point based on the first 10 characters of the sha1 of its text representation and saves the link in the kill ring. Thus you can invoke it, move to the transaction to be linked and insert the link to the first transaction with `C-y`.

**Comment by nils-werner** [comment]
Sounds good, thanks
