### ISSUE TITLE
bean-format: accept multiple files at once

### ISSUE THREAD

**Issue by blaggacao** [beancount/beancount#689]
According to nascent https://github.com/numtide/treefmt/blob/master/docs/formatters-spec.md, formatters should accept `[...<files>]`.

See also: https://github.com/numtide/treefmt/issues/77#issuecomment-994823444

^^ I know it is bold to postulate that spec as authoritative. I thought, it's worth trying, though, since the big majority of formatters already "complied" ex ante.

**Comment by blais** [comment]
I don't see how this has anything to do with anything. You probably commented on the wrong project by accident.

**Comment by dnicolodi** [comment]
I think @blaggacao was proposing to make `bean-format` accept multiple input files on the command line. The only way to make that work reasonably, and what `treefmt` expects, is to have `bean-format` rewrite the input files in place, and `bean-format` does not work like this. I didn't investigate what `treefmt` aims to be but at a first glance I don't think it has much relevance for Beancount (and I don't share the excitement for automatic code formatting: I don't think that freeing  programmers from the menial task of code formatting to allow them to publish more cokie-cutter single-functions Javascript modules on npm is a worthy goal).

**Comment by blaggacao** [comment]
> You probably commented on the wrong project by accident.

Hahah, for a moment I believed that based on your reply, but indeed the request is to let `bean-format` handle `[<file> ...]` instead of `[<file>]`.

Without news I'd assume that this request is understood as beeing declined.

@dnicolodi is right, it would require bean-format to rewrite files "in-place" / via tmp-files.

In my opinion, the mentioned tooling reasonably expects formatters to handle multiple input paths or sometimes even implement a tree walker for that matter.
