### ISSUE TITLE
bean-extract fails to import transaction depending on arbitrary fields

### ISSUE THREAD

**Issue by mtlynch** [beancount/beancount#696]
I'm running into strange behavior with an importer, and it seems like it may be a bug in Beancount.

My importer has an `extract` method that I've simplified for debugging purposes to return a single transaction:

```python
    def extract(self, f):
        d = data.Transaction(meta=data.new_metadata("dummy", 1),
                             date=datetime.date(2021, 12, 2),
                             flag=self.FLAG,
                             payee='Dummy Payee',
                             narration=None,
                             tags=data.EMPTY_SET,
                             links=data.EMPTY_SET,
                             postings=[
                                 data.Posting(account=self._account,
                                              units=amount.Amount(
                                                  number.D('1868.26'), 'USD'),
                                              cost=None,
                                              price=None,
                                              flag=None,
                                              meta=None),
                                 data.Posting(account='Income:Dummy',
                                              units=None,
                                              cost=None,
                                              price=None,
                                              flag=None,
                                              meta=None)
                             ])
        return [d]
```

And my ledger looks like this:

```text
option "title" "Dummy Ledger"
option "operating_currency" "USD"

2021-01-01 open Assets:Checking
2021-01-01 open Income:Dummy

2021-11-30 * "Dummy" ""
  Assets:Checking  1779.31 USD
  Income:Dummy
```

When I run my importer, I'd expect it to emit the hardcoded transaction from my importer, but it just emits a blank line. But what's interesting is that if I change seemingly unimportant fields, it *does* emit the transaction.

For example, if I change the existing transaction in the ledger to `21779.31`, then run the importer, it correctly emits the transaction in the `extract` method. Same thing if I change the date in the `extract` method's transaction to `2021, 10, 2`. That emits the transaction.

## To repro

```bash
cd $(mktemp -d) && \
  git clone https://github.com/mtlynch/beancount-repro.git . && \
  docker build -t beancount . && \
  docker run -it -v "${PWD}:/app" -w /app --entrypoint /app/repro beancount
```

### Expected

```text
;; -*- mode: beancount -*-
**** /app/downloads/transactions.csv

2021-12-02 * "Dummy Payee" ""
  Assets:Checking  1868.26 USD
  Income:Dummy
```

### Actual

```text
;; -*- mode: beancount -*-
**** /app/downloads/transactions.csv

; 2021-12-02 * "Dummy Payee" ""
;   Assets:Checking  1868.26 USD
;   Income:Dummy
```

But then change the amount of the transaction in `repro.beancount`, and re-run `docker run -it -v "${PWD}:/app" -w /app --entrypoint /app/repro beancount` - the transactions will be emitted.

**Comment by dnicolodi** [comment]
This is expected. `bean-extract` implements deduplication of the transactions emitted by the importers against the transactions in the existing ledger. The deduplication considers transactions that happen within 2 days of each other and whose amounts differ by less than 5% to be duplicates. Unfortunately this is not easy to configure. If you don' want deduplication, don't pass an existing ledger to `bean-extract`. Beangulp will make this configurable by the importer.

**Comment by mtlynch** [comment]
Oh, that's surprising. I've been using Beancount for a year, and I don't think I've ever run into this before.

Thanks for the explanation!

**Comment by dnicolodi** [comment]
This feature could be documented better, indeed. The implementation has comments with some details https://github.com/beancount/beancount/blob/v2/beancount/ingest/similar.py#L19
