### ISSUE TITLE
Different "event" name suggestion

### ISSUE THREAD

**Issue by jenicek** [beancount/beancount#697]
Hi, I was reading through the comprehensive documentation (which I really appreciate as a beginner) and came across the [appeal](https://beancount.github.io/docs/beancount_language_syntax.html#fn:3) for a different name for "event". I believe the best-suited name would be "log", as it is used commonly even outside of IT for exactly this purpose - keeping track of some "variable", where the records are usually related to a change of position, weather, or time.

**Comment by blais** [comment]
That's a nice idea. I'll keep it mind for v3. (The ship has sailed a long time ago for v1)
Thank you,
