### ISSUE TITLE
failed build master branch on macOS (bazel m1)

### ISSUE THREAD

**Issue by shuxiao9058** [beancount/beancount#711]

**Comment by shuxiao9058** [comment]
tensorflow_io can not build on m1 chip Mac
.

**Comment by dnicolodi** [comment]
Tensorflow is not used in Beancount thus the fact that tensorflow_io is pulled in by the Bazel build is probably a shortcoming of the build system. However, building Beancount with Bazel is currently used only for the development of the C++ part of the codebase that is not yet integrated into the Python application. Thus, unless you are planning on contributing to the C++ codebase, there is no reason to build Beancount with Bazel. Being a developers only build, it is very rough around the edges and some assembly may be required to get it going.

All that said, if tensorflow_io does not build on M1 Macs, it would be better to report it on the tensorflow_io issue tracker.

**Comment by shuxiao9058** [comment]
also failed build with latest ubuntu(21.04), but success with ubuntu LTS .

do you mean that the 3.0 version of beancount do not required built with Bazel ?

**Comment by dnicolodi** [comment]
Beancount 3.0 does not exist yet. There is only a development branch for what may become Beancount 3.0. Getting an usable application out of this branch does not require building with Bazel. I somehow understand that everyone wants to use the latest and greatest, but it would be better to understand the implications of using a development branch. If you are unsure about which version of Beancount you should use, I suggest reading this https://groups.google.com/g/beancount/c/h3YHCz44lIU/m/UTwQlue_DwAJ

**Comment by daniel0076** [comment]
Seeing someone trying to build beancount v3 on non-Linux machines, I would like to point out an issue that current beancount implementation relies on platform dependent calls and is not written to be portable on unix-like or POSIX machines.

The file `beancount/utils/errors.cc` used `error.h` which is Linux only, while the equivalent counterpart on FreeBSD or macOS is `errno.h`, of course the call `strerror_r()` is different on the platforms accordingly. There can be some other parts that I haven't noticed yet, as the project looks like to be platform independent (no matter using or developing), I think perhaps this should be handled?

This is just FYI, however, as you mentioned, `bazel` have more complicated external dependencies comparing to some other modern build systems like `cmake`, is there any plan to also provide other build systems?

**Comment by blais** [comment]
Daniel, I think given the small amount of attention I've been able to bring to the v3 rewrite in the last year or two, it's safe to say that supporting multiple build system is way at the bottom of the list. I have a month of time coming up and I'd like to bring the Bazel build up to date (the changes I've been hanging for in proto 4 are now in I believe) and restart coding on the core library; I wouldn't expect explicit support for Mac/Windows from me, perhaps others will step in once the new C++ functionality is hooked up and usable.

**Comment by daniel0076** [comment]
Hi Balis, 
with no doubt, the build system and cross-platform supports are a lot trivial comparing to the core library development. Thanks for the great library and really looking forward to the new C++ functionalities.
In fact I have made an adoption of v3 on `macOS` with `cmake` for a experimental project, and perhaps I can contribute those once the main functions of new version is stable. 😄

**Comment by dnicolodi** [comment]
There is already a PR adding a Meson build definition for the C++ code in v3 #612. With the recent improvements in the tooling for generating Python wheels (distributable Python binary packages) from Meson (supported by the SciPy and Numpy folks) I may update it soon. One nice thing of this approach is that it easily allows to build wheels with all (Python and non-Python) dependencies pinned (using Meson subprojects for the non-Python dependencies) as the Bazel build does. As far as I know Bazel does not have a solution for generating Pythion wheels from the build artifacts.

**Comment by dnicolodi** [comment]
This bug is about experimental code that has been removed. Closing.
