### ISSUE TITLE
`bean-format` does not support arithmetic expressions in balance assertions

### ISSUE THREAD

**Issue by ambroisie** [beancount/beancount#714]
The following input:

```beancount
2000-01-01 balance Assets:Example (10.00 - 0.01) EUR
2000-01-01 balance Assets:Example 9.99 EUR
```

Run through `bean-format -c 80`, leads to the following output;

```beancount
2000-01-01 balance Assets:Example (10.00 - 0.01) EUR
2000-01-01 balance Assets:Example                                         9.99 EUR
```

**Comment by ambroisie** [comment]
I thought it was only `bean-format -c`, but actually even when using `-w` and `-W` I still have those lines non-formatted.

**Comment by dnicolodi** [comment]
`bean-format` is an hack based on regular expressions, not on a complete parser of the Beancount syntax. I don't think there is an easy way to make it support arithmetic expressions. There are plans to extend the Beancount parser to emit a complete syntax three that could be used to programmatically reformat the ledger, but it is a bit of work till we get there.

**Comment by ambroisie** [comment]
I know that it's a hack, but *if* we could account for at least very simple arithmetic expressions (which is still possible with regular expressions, as I am not talking about arbitrary recursion but simply adding binary operations), this kind of statement could be formatted correctly :-)

**Comment by dnicolodi** [comment]
Sure, patches to support it are more than welcome.
