### ISSUE TITLE
Show booked date in holdings report in bean-web

### ISSUE THREAD

**Issue by muks** [beancount/beancount#717]
In the holdings report from `bean-web`, is it possible to also show the booked date alongside the book value, so that it is possible to quickly identify the transaction that acquired the holding?

(I also request you to preserve `bean-web` and not remove it in a future version of beancount. Although there are other UIs such as Fava, `bean-web` is simple, light, clean and presents sufficient information.)

**Comment by dnicolodi** [comment]
`bean-web` is dead for good but I think it can be resurrected outside Beancount core if someone is interested in maintaining it. One important issue with keeping `bean-web` alive is that it is bases on a web framework (Bottle) that AFAIK is not actively maintained and which has increasingly outdated dependencies that make installing it into a modern Python environment increasingly difficult. In the current state there is not enough manpower to tend to it let alone port it to some other web framework.

**Comment by dnicolodi** [comment]
No one showed interest in maintaining it so `bean-web` is gone. Closing this issue.
