### ISSUE TITLE
bean-web shows a different Balance Sheet and Trial Balance 

### ISSUE THREAD

**Issue by itpetarabia** [beancount/beancount#735]
I'm running the following beancount file
```
option "operating_currency" "USD"
option "operating_currency" "GBP"

plugin "beancount.plugins.implicit_prices"

2020-01-01 open Expenses:Things
2020-01-01 open Assets:Current
2020-01-01 open Equity:Conversions:Current

2020-06-01 * "Bought a widget online"
  Expenses:Things   50.00 USD @@ 100.00 GBP
  Assets:Current                -100.00 GBP

2020-07-01 * "Bought a widget online"
  Expenses:Things   50.00 USD @@ 110.00 GBP
  Assets:Current                -110.00 GBP

2020-08-01 * "Bought a widget online (in GBP)"
  Expenses:Things                 90.00 GBP
  Assets:Current                 -90.00 GBP
```

Below is the generated balance sheet for that file, with a new account created -> Equity:Conversions:Current
![Screenshot from 2022-11-09 17-25-57](https://user-images.githubusercontent.com/89512629/200857970-5a239e3a-5b92-44be-8a82-9f3de22c865e.png)

However I don't see the same set of Equity accounts under the Trial Balance. I even tried to be explicit and write an open directive. The missing conversions account is frustrating because I can't seem to make the TB balance
![Screenshot from 2022-11-09 17-25-40](https://user-images.githubusercontent.com/89512629/200858543-b2a7a872-dd90-4891-b7e3-3bb4c742ab0b.png)

**Comment by dnicolodi** [comment]
No one showed interest in maintaining it so `bean-web` has been removed. Closing this issue.
