### ISSUE TITLE
Add a bazel module to bazel-central-registry for beancount3

### ISSUE THREAD

**Issue by doug** [beancount/beancount#736]
Would be helpful to add a bazel module to https://bazel.build/build/bzlmod via https://github.com/bazelbuild/bazel-central-registry. So that beancount3 can be experimented on as bazel module. Would need a tagged v3 release and some configuration setup in the bazel-central-registry.

**Comment by dnicolodi** [comment]
Bazel is not used anymore as the build system for Beancount. Closing.
