### ISSUE TITLE
What is the official guidance on indentation in Beancount's syntax?

### ISSUE THREAD

**Issue by MTPeyton** [beancount/beancount#743]
Hi all! I've been trying to figure out the ideal way of organizing my Beancount file via indentation. Right now it follows this format:

```
;# 2020 Transactions
;# 2021 Transactions
;# 2022 Transactions
    ;# 2022-01
    ;# 2022-02
    ;# 2022-03
        ;# Cash
        ;# Banking
            2022-03-15 * "Move money from checking to savings"
                Assets:Checking -1 USD
                Assets:Savings 1 USD

            2022-03-16 * "Withdraw money from ATM"
                Assets:Checking -1 USD
                Assets:Wallet 1 USD

        ;# Credit Cards
    ;# 2022-04
;# 2023 Transactions
```

The benefit of this format is that it allows me to use the folding feature of https://github.com/Lencerf/vscode-beancount to collapse sections I'm not working on. (e.g. If I'm working on March 2022, then I only have that section open, with the rest folded/collapsed. If I want to compare to March 2021, I could just unfold the 2021 Transactions section, then unfold 2021-03)

However, this means that transactions and postings can have an arbitrary (multiple of 4) amount of spaces indenting them. `bean-check` does NOT like this, and returns thousands of "syntax error, unexpected INDENT" errors. Some tools like `fava` are robust against this, and still work fine. Even the VSCode extension doesn't complain about this format. However other tools, like `bean-price`, are not robust against this.

**My main question is: what are the official standards around indentation (and whitespace in general) for Beancount's syntax?** I tried to search for "indent" and "whitespace" in the official documentation... but I didn't find much guidance.

**Comment by dnicolodi** [comment]
Questions regarding the use of Beancount are better addressed to the mailing list https://groups.google.com/g/beancount

The Beancount syntax is described in detail in the manual https://beancount.github.io/docs/beancount_language_syntax.html The documentation does not say that you can use arbitrary indentation. It was thought that this was enough to make the reader conclude that arbitrary indentation is not supported.

AFAIK all the tools you mention use the same parser to interpret the Beancount ledger. The parser is fairly robust and recovers quickly on syntax errors, thus the errors are reported but the parsing goes on. I haven't tried but probably the transactions are extracted correctly despite the funny indentation. It seems that Fava simply discards the parsing errors. I don't see this as a feature. The fact that the Beancount tools complain about the syntax is further indication that arbitrary indentation is not supported.

The Emacs mode for Beancount ledgers https://github.com/beancount/beancount-mode/ does not need indentation to support sections folding. I'm sure VSCode can be persuaded to do the same thing.

**Comment by MTPeyton** [comment]
That makes sense, thank you!

I think I'm just going to break each month into its own file, strip out the indentation from each one, then use the import directive to combine all of those.
