### ISSUE TITLE
CSV importer regular expressions only match content and not filename

### ISSUE THREAD

**Issue by doughepi** [beancount/beancount#747]
Unless I'm missing something or using CSV importer incorrectly, the content of a file is the only thing that is matched against the regular expressions passed into the CSV importer constructor.

https://github.com/beancount/beancount/blob/6d64d56b2e04dd164cd117c124d703da89783ee1/beancount/ingest/importers/csv.py#L180

I believe this is useful, but falls short in instances where the data directory you're importing from contains files with similar CSV structures, but represent different accounts. In such a case, no account specific information is available in the content of the CSV, only the title (i.e. a 4 digit account postfix like ChaseXXXX). The CSV importer would match multiple files representing different accounts because the current `regexps` parameter only allows regular expression matching on file content (usually the CSV header row is matched). 

Suggested improvement would be to allow for a `content_regexps` and `filename_regexp` to be specified in the csv.Importer constructor, instead of just the `regexes` list that is currently implemented.

**Comment by dnicolodi** [comment]
The CVS `Importer` inherits form the `IdentifyMixin`. If you look at the implementation of the mixin you can see that you can instantiate the CSV `Importer` with a `filename` taking a regular expression to match the file name.

**Comment by doughepi** [comment]
Ah, I see that now. You're right!

For others' future reference, this is what I ended up using.

```python
chase_sapphire_reserve_importer = csv.Importer(
    {
        Col.DATE: "Post Date",
        Col.PAYEE: "Description",
        Col.AMOUNT: "Amount",
    },
    "Liabilities:Current-Liabilities:Credit-Cards:Chase:Sapphire-Reserve",
    "USD",
    ("Transaction Date,Post Date,Description,Category,Type,Amount,Memo"),

    # Regular expression that matches just the Chase0000 portion of Chase0000_Activity20230101_20230228_20230228.CSV
    matchers=[
        ("filename", r"Chase0000_Activity.*\.CSV")
    ]
)
```


I would still think that a `filename_regexp` would be a suitable usability improvement for the csv.Importer API but this works for now!

I'm going to close this issue now.
