### ISSUE TITLE
Step-by-step tutorial needed: How to compute CGT tax?

### ISSUE THREAD

**Issue by iirekm** [beancount/beancount#748]
I found some documentation on 'Inventories' at https://beancount.github.io/docs/how_inventories_work.html, but I don't get it, it's too 'theoretical', doesn't show how to use it to compute yearly CGT report with FIFO method?. 

More step-by-step instructions would be needed:
- prepare directives in format  `.....`
- issue the command `.....` to generate CGT report

**Comment by blais** [comment]
SGTM you should write it.
