### ISSUE TITLE
PyPi install errors : testresources, pip3.8

### ISSUE THREAD

**Issue by tsc-pygy** [beancount/beancount#752]
To the people who probably won't read this...

Now that my system is bloated from trying to install the long list of dependencies for beancount, I guess I'll quit while I'm behind. Just ignore everything below. I'll use Ledger instead.

The message "Successfully built beancount" did occur (below), which seemed promising, but the errors threw me off.

If the errors regarding testresources and pip3.8 won't affect the functionality of the program, please let me know. My concern is that I don't want to trust my financial information to a faulty installation of beancount.

Please let me know if you need more information.
Thank you for any assistance you can provide!

OS : Linux Mint 20.1
Device : Lenovo Ideapad 310

$ apt install python3-dev

[sudo] password:
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python3-dev is already the newest version (3.8.2-0ubuntu2).
python3-dev set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

$ pip3 
   (also tried pip3.8 -> same output)

Usage:   
  pip3 <command> [options]

Commands:
  install                     Install packages.
  download                    Download packages.
  uninstall                   Uninstall packages.
  freeze                      Output installed packages in requirements format.
  list                        List installed packages.
  ... etc.
 
General Options:
  -h, --help                  Show help.
  --debug                     Let unhandled exceptions propagate outside the main subroutine, instead of logging them to
                              stderr.
  --isolated                  Run pip in an isolated mode, ignoring environment variables and user configuration.
  --require-virtualenv        Allow pip to only run in a virtual environment; exit with an error otherwise.
  -v, --verbose               Give more output. Option is additive, and can be used up to 3 times.
  ...etc.

$ sudo -H python3 -m pip install beancount

Collecting beancount
  Downloading beancount-2.3.5.tar.gz (638 kB)
     |████████████████████████████████| 638 kB 491 kB/s 
Requirement already satisfied: beautifulsoup4 in /usr/lib/python3/dist-packages (from beancount) (4.8.2)
Collecting bottle
  Downloading bottle-0.12.25-py3-none-any.whl (90 kB)
     |████████████████████████████████| 90 kB 846 kB/s 
Requirement already satisfied: chardet in /usr/lib/python3/dist-packages (from beancount) (3.0.4)
Collecting google-api-python-client
  Downloading google_api_python_client-2.83.0-py2.py3-none-any.whl (11.2 MB)
     |████████████████████████████████| 11.2 MB 3.4 MB/s 
Collecting lxml
  Downloading lxml-4.9.2-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl (7.1 MB)
     |████████████████████████████████| 7.1 MB 3.9 MB/s 
Collecting ply
  Downloading ply-3.11-py2.py3-none-any.whl (49 kB)
     |████████████████████████████████| 49 kB 1.8 MB/s 
Collecting pytest
  Downloading pytest-7.2.2-py3-none-any.whl (317 kB)
     |████████████████████████████████| 317 kB 3.7 MB/s 
Requirement already satisfied: python-dateutil in /usr/lib/python3/dist-packages (from beancount) (2.7.3)
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from beancount) (2.22.0)
Requirement already satisfied: python-magic>=0.4.12 in /usr/lib/python3/dist-packages (from beancount) (0.4.16)
Collecting google-auth-httplib2>=0.1.0
  Downloading google_auth_httplib2-0.1.0-py2.py3-none-any.whl (9.3 kB)
Collecting google-auth<3.0.0dev,>=1.19.0
  Downloading google_auth-2.17.0-py2.py3-none-any.whl (178 kB)
     |████████████████████████████████| 178 kB 5.3 MB/s 
Collecting uritemplate<5,>=3.0.1
  Downloading uritemplate-4.1.1-py2.py3-none-any.whl (10 kB)
Collecting google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5
  Downloading google_api_core-2.11.0-py3-none-any.whl (120 kB)
     |████████████████████████████████| 120 kB 4.1 MB/s 
Collecting httplib2<1dev,>=0.15.0
  Downloading httplib2-0.22.0-py3-none-any.whl (96 kB)
     |████████████████████████████████| 96 kB 2.1 MB/s 
Collecting tomli>=1.0.0; python_version < "3.11"
  Downloading tomli-2.0.1-py3-none-any.whl (12 kB)
Collecting iniconfig
  Downloading iniconfig-2.0.0-py3-none-any.whl (5.9 kB)
Collecting exceptiongroup>=1.0.0rc8; python_version < "3.11"
  Downloading exceptiongroup-1.1.1-py3-none-any.whl (14 kB)
Requirement already satisfied: packaging in /usr/lib/python3/dist-packages (from pytest->beancount) (20.3)
Collecting attrs>=19.2.0
  Downloading attrs-22.2.0-py3-none-any.whl (60 kB)
     |████████████████████████████████| 60 kB 2.2 MB/s 
Collecting pluggy<2.0,>=0.12
  Downloading pluggy-1.0.0-py2.py3-none-any.whl (13 kB)
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from google-auth-httplib2>=0.1.0->google-api-python-client->beancount) (1.14.0)
Collecting cachetools<6.0,>=2.0.0
  Downloading cachetools-5.3.0-py3-none-any.whl (9.3 kB)
Collecting rsa<5,>=3.1.4; python_version >= "3.6"
  Downloading rsa-4.9-py3-none-any.whl (34 kB)
Collecting pyasn1-modules>=0.2.1
  Downloading pyasn1_modules-0.2.8-py2.py3-none-any.whl (155 kB)
     |████████████████████████████████| 155 kB 4.2 MB/s 
Collecting googleapis-common-protos<2.0dev,>=1.56.2
  Downloading googleapis_common_protos-1.59.0-py2.py3-none-any.whl (223 kB)
     |████████████████████████████████| 223 kB 4.1 MB/s 
Collecting protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.19.5
  Downloading protobuf-4.22.1-cp37-abi3-manylinux2014_x86_64.whl (302 kB)
     |████████████████████████████████| 302 kB 3.8 MB/s 
Requirement already satisfied: pyparsing!=3.0.0,!=3.0.1,!=3.0.2,!=3.0.3,<4,>=2.4.2; python_version > "3.0" in /usr/lib/python3/dist-packages (from httplib2<1dev,>=0.15.0->google-api-python-client->beancount) (2.4.6)
Collecting pyasn1>=0.1.3
  Downloading pyasn1-0.4.8-py2.py3-none-any.whl (77 kB)
     |████████████████████████████████| 77 kB 2.6 MB/s 
Building wheels for collected packages: beancount
  Building wheel for beancount (setup.py) ... done
  Created wheel for beancount: filename=beancount-2.3.5-cp38-cp38-linux_x86_64.whl size=823145 sha256=b4897d530bd72c4c3ddd9b1ed095f19403aa27c133f9df327fc328f9189612c6
  Stored in directory: /root/.cache/pip/wheels/c2/3b/b5/8eee05eeda6eacd53404016a9aeb28ced036c8e29a6c1670c5

Successfully built beancount

ERROR: launchpadlib 1.10.13 requires testresources, which is not installed.

Installing collected packages: bottle, httplib2, cachetools, pyasn1, rsa, pyasn1-modules, google-auth, google-auth-httplib2, uritemplate, protobuf, googleapis-common-protos, google-api-core, google-api-python-client, lxml, ply, tomli, iniconfig, exceptiongroup, attrs, pluggy, pytest, beancount
  Attempting uninstall: httplib2
    Found existing installation: httplib2 0.14.0
    Not uninstalling httplib2 at /usr/lib/python3/dist-packages, outside environment /usr
    Can't uninstall 'httplib2'. No files were found to uninstall.
  Attempting uninstall: protobuf
    Found existing installation: protobuf 3.6.1
    Not uninstalling protobuf at /usr/lib/python3/dist-packages, outside environment /usr
    Can't uninstall 'protobuf'. No files were found to uninstall.
Successfully installed attrs-22.2.0 beancount-2.3.5 bottle-0.12.25 cachetools-5.3.0 exceptiongroup-1.1.1 google-api-core-2.11.0 google-api-python-client-2.83.0 google-auth-2.17.0 google-auth-httplib2-0.1.0 googleapis-common-protos-1.59.0 httplib2-0.22.0 iniconfig-2.0.0 lxml-4.9.2 pluggy-1.0.0 ply-3.11 protobuf-4.22.1 pyasn1-0.4.8 pyasn1-modules-0.2.8 pytest-7.2.2 rsa-4.9 tomli-2.0.1 uritemplate-4.1.1

$ pip install testresources

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: testresources in ./.local/lib/python3.8/site-packages (2.0.1)
Requirement already satisfied: pbr>=1.8 in ./.local/lib/python3.8/site-packages (from testresources) (5.6.0)

--- Logging error ---
Traceback (most recent call last):
  File "/home/<user>/.local/lib/python3.8/site-packages/pip/_internal/utils/logging.py", line 177, in emit
    self.console.print(renderable, overflow="ignore", crop=False, style=style)
  File "/home/<user>/.local/lib/python3.8/site-packages/pip/_vendor/rich/console.py", line 1752, in print
    extend(render(renderable, render_options))
  File "/home/<user>/.local/lib/python3.8/site-packages/pip/_vendor/rich/console.py", line 1390, in render
    for render_output in iter_render:
  File "/home/<user>/.local/lib/python3.8/site-packages/pip/_internal/utils/logging.py", line 134, in __rich_console__
    for line in lines:
  File "/home/<user>/.local/lib/python3.8/site-packages/pip/_vendor/rich/segment.py", line 245, in split_lines
    for segment in segments:
  File "/home/<user>/.local/lib/python3.8/site-packages/pip/_vendor/rich/console.py", line 1368, in render
    renderable = rich_cast(renderable)
  File "/home/<user>/.local/lib/python3.8/site-packages/pip/_vendor/rich/protocol.py", line 36, in rich_cast
    renderable = cast_method()
  File "/home/<user>/.local/lib/python3.8/site-packages/pip/_internal/self_outdated_check.py", line 130, in __rich__
    pip_cmd = get_best_invocation_for_this_pip()
  File "/home/<user>/.local/lib/python3.8/site-packages/pip/_internal/utils/entrypoints.py", line 58, in get_best_invocation_for_this_pip
    if found_executable and os.path.samefile(
  File "/usr/lib/python3.8/genericpath.py", line 101, in samefile
    s2 = os.stat(f2)

FileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/pip3.8'

Call stack:
  File "/home/<user>/.local/bin/pip", line 8, in <module>
    sys.exit(main())
  File "/home/<user>/.local/lib/python3.8/site-packages/pip/_internal/cli/main.py", line 70, in main
    return command.main(cmd_args)
  File "/home/<user>/.local/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 101, in main
    return self._main(args)
  File "/home/<user>/.local/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 223, in _main
    self.handle_pip_version_check(options)
  File "/home/<user>/.local/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 148, in handle_pip_version_check
    pip_self_version_check(session, options)
  File "/home/<user>/.local/lib/python3.8/site-packages/pip/_internal/self_outdated_check.py", line 237, in pip_self_version_check
    logger.info("[present-rich] %s", upgrade_prompt)
  File "/usr/lib/python3.8/logging/__init__.py", line 1446, in info
    self._log(INFO, msg, args, **kwargs)
  File "/usr/lib/python3.8/logging/__init__.py", line 1589, in _log
    self.handle(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 1599, in handle
    self.callHandlers(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 1661, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 954, in handle
    self.emit(record)
  File "/home/<user>/.local/lib/python3.8/site-packages/pip/_internal/utils/logging.py", line 179, in emit
    self.handleError(record)

Message: '[present-rich] %s'
Arguments: (UpgradePrompt(old='22.1.2', new='23.0.1'),)

$ python3 -m beancount.scripts.deps -> no ouput

Thanks for your time!

**Comment by blais** [comment]
This might be the error?
`FileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/pip3.8'`

Have fun with Ledger,
