### ISSUE TITLE
How to convert beancount file to parquet schema for visualization?

### ISSUE THREAD

**Issue by jaanaltosaar** [beancount/beancount#755]
Hi! At our health AI nonprofit we need to have full transparency to engender trust.

We're considering using beancount - but haven't figured out how to visualize the transaction history.

We need to use Vega / Altair in Python -- but not sure how to convert the beancount format file into a parquet file for visualization.

Has anyone used Vega / Altair for visualizing beancount data? 

Here's an example:

https://vega.github.io/falcon/flights/

Thank you!!
Jaan

**Comment by dnicolodi** [comment]
This question is too open ended to be answered in any meaningful way. The information recorded in a Beancount ledger (or any double entry accounting system) is not tabular in nature, therefore recording it into any kind of tabular storage requires some reduction or join of the ledger data. If the question is more practical, the only think you need is to iterate the data structures returned by `beancount.loader.load_file()` and import the data you need into your preferred data container.

**Comment by blais** [comment]
This type of thing has been done in Fava.
