### ISSUE TITLE
Error "Could not build wheels for beancount" occurred when installing beancount

### ISSUE THREAD

**Issue by ElvisUpUp** [beancount/beancount#759]
Error "Could not build wheels for beancount" occurred when installing beancount

![image](https://github.com/beancount/beancount/assets/31996660/6103e1c2-b0e2-425d-8748-7f72af417fcb)

**Comment by BelNeal** [comment]
I am having the same issue after cleaning up my Venv.

**Comment by dnicolodi** [comment]
There is not enough information for making this bug report actionable. Please run the build with verbose logging and report the full output.

**Comment by BelNeal** [comment]
My solution was the system env variables for visual studio c++ 14.0.

**Comment by dnicolodi** [comment]
The `beancount` package contains Python extension modules. A working C compiler is a prerequisite to compile them. If that is all it takes to have the package built correctly, I don't see anything wrong with the beancount source package.

**Comment by trim21** [comment]
@blais maybe we should tag a new version to release a python 3.11 windows wheel?

**Comment by LaoshuBaby** [comment]
Are you using python 3.11? I meet with this problem and curious about why it need to build on my PC:

https://pypi.org/project/beancount/2.3.5/#files

Oh, its latest version only have whl file for cp310

<img src="https://github.com/beancount/beancount/assets/42690037/ad0dbb05-7282-47af-808f-c04dca47f2df" width=500px/>

![图片](https://github.com/beancount/beancount/assets/42690037/30c8c565-711d-4eb3-b4e2-63980f2d49da)

I found this issue so I don't need to duplicate one, ~~I'll try whether MS's build tool works.~~ 

~~Oh no it need my 12.5GB free disk space, I surrender！~~

Success, it works, you need to build install

**Comment by trim21** [comment]
https://github.com/beancount/beancount/issues/778 related issues

> Sorry guys, I can't fix this soon. If you care about a Windows wheel, please backport the setup from the master feature and send me a PR, I'll rubberstamp it.

**Comment by dnicolodi** [comment]
Beancount 2.3.6 has been released and wheels all supported Python versions for all major platforms have been uploaded to PyPI.
