### ISSUE TITLE
Attempting to install beancount from source results in an incomplete install of the 3.0.0.dev version

### ISSUE THREAD

**Issue by FizzesShark** [beancount/beancount#771]
Following the instructions [here](https://beancount.github.io/docs/installing_beancount.html), I attempted to install beancount from source by cloning the repository and running the command `sudo -H python3 -m pip install .`

This resulted in a successful pip command call, but after looking through the installed packages, it looked very bare:
<img width="358" alt="Screenshot 2023-09-16 at 4 32 28 PM" src="https://github.com/beancount/beancount/assets/12519650/e49e065e-512b-4b11-b9de-8977723c1ed7">
And indeed, after trying to run any command, such as for example, `bean-check`, I get an error as follows:
<img width="449" alt="Screenshot 2023-09-16 at 4 33 20 PM" src="https://github.com/beancount/beancount/assets/12519650/989801f9-728a-42dc-bfde-89be39075258">

In fact, the same error results when trying to install the pip package as well. For reference, I'm on Mac OS Ventura 13.1, and am using Python 3.11.

**Comment by dnicolodi** [comment]
What do you mean with "bare"? `beancount` and its dependencies are listed in the installed packages.

That is not an error but a warning, everything is working as expected.

**Comment by FizzesShark** [comment]
Well, that was embarrassing! Totally thought the command was breaking
