### ISSUE TITLE
Accounts with Unicode chars don't work well with bean-web

### ISSUE THREAD

**Issue by cdokolas** [beancount/beancount#786]
I have some accounts named with Greek words. Clicking on them in the `bean-web` micro-site, gives an `Error: 400 Bad Request` error with the following info:

`Invalid path string. Expected UTF-8`

For testing purposes, I opened an account named `Liabilities:Test:αβγδε`. The resulting URL is `http://localhost:8080/view/all/journal/Liabilities:Test:%CE%B1%CE%B2%CE%B3%CE%B4%CE%B5` and the URL-part of the error is `Sorry, the requested URL 'http://localhost:8080/view/all/journal/Liabilities%3ATest%3A%CE%B1%CE%B2%CE%B3%CE%B4%CE%B5' caused an error`.

**Comment by dnicolodi** [comment]
`bean-web` is deprecated, it is not maintained anymore, and it will not be part of the next major release of Beancount. A fix for this issue could be included in the next 2.3.x bugfix release, but someone would need to contribute the fix.

**Comment by cdokolas** [comment]
I was under the impression that 2.x is the current production version and some maintenance is expected. Thanks for considering this fix.

Will something similar be available in v3.x? I find the web interface particularly useful for checking _and_ quick-viewing the current state of the ledger.

**Comment by dnicolodi** [comment]
> I was under the impression that 2.x is the current production version and some maintenance is expected.

As in any other open source project maintained by volunteers, you can expect maintenance as long as someone is motivated enough to do the work. The ones doing most of the work on beancount do not have interest in `bean-web`, thus I don't expect anyone of the regular contributors to fix this bug. If you can contribute a patch, or sponsor someone to work on a patch, we will do our best to review it and include it in the next release.

> Will something similar be available in v3.x?

Fava is another web interface, although, last time I checked, it does not work out of the box with Beancount 3.0

**Comment by cdokolas** [comment]
@dnicolodi Understood. Unfortunately, I'm not good with Python to help.

**Comment by dnicolodi** [comment]
`bean-web` has been discontinued
