### ISSUE TITLE
Commodity starting with number char

### ISSUE THREAD

**Issue by askarzh** [beancount/beancount#792]
It is not allowed to use comodity name with starting number char. Unfortunately, there is some stocks with number at first. I.e.
2B78 iShares Healthcare Innovation UCITS ETF
EUR:yahoo/2B78.DE

**Comment by blais** [comment]
Sorry won't do. Unnecessary parser complications involved.
I think you should just decide on a (non-numerical) prefix.

**Comment by mattmccormick** [comment]
I would like to vote that this be re-opened.  Bonds and T-Bills are normally identified with mostly numbers.

**Comment by dnicolodi** [comment]
@mattmccormick There is no reason why the commodity symbol used in the beancount ledger and the identifier of the T-Bills need to be the same. I would argue that the numerical T-Bill identifier is the less ergonomic choice to put in your ledger. I'm not familiar with US treasure bills, but I think it is not straightforward to go from their numerical identifier to their expire date or yield, which are the information that you most likely care the most about. If you really want to use the numerical identifier, just prepend a prefix.

**Comment by blais** [comment]
Just put a T in front of it.
