### ISSUE TITLE
Commdity directive support for T-Bills (CUSIP)

### ISSUE THREAD

**Issue by pallavg** [beancount/beancount#794]
I try to capture a Treasury Bill by CUSIP number as follows:

```
2023-01-01 commodity 912828P38
  name: "T-Bill"
  asset-class: "T-Bill"
  cusip: "912828P38"
  export: "912828P38"
  price: ""
```

When I run bean-check, I get the following error:

` syntax error, unexpected NUMBER, expecting CURRENCY`

As a workaround, I change 912828P38 to T912828P38 to get past the error. Is this behavior expected? What would be the correct way to capture T-Bills. Unlike ETF/Stocks which have letters, T-Bills are usually defined by CUSIP numbers ASFAIK. Thanks.

**Comment by blais** [comment]
That's correct and your solution to it very nice.

**Comment by pallavg** [comment]
Thanks. I will close this as it is a non-issue now.
