### ISSUE TITLE
BQL: convert function does the convertion at the current date, not at the date of the transaction

### ISSUE THREAD

**Issue by olegbbtr** [beancount/beancount#798]
Perhaps, `sum(convert(cost(position), ...) )` should give conversion at  the date of the posting, but `convert(sum(...), ...)` should give it at a current date.

**Comment by dnicolodi** [comment]
`convert()` works as documented. If you want to convert at the date of the transaction, use `convert(cost(position), 'COMMODITY', date)`. Changing the definition of the `convert()` function would obviously break backward compatibility, thus it is not going to happen.
