### ISSUE TITLE
Convert float arguments to string first before calling Decimal

### ISSUE THREAD

**Issue by mattmccormick** [beancount/beancount#800]
In the [code here](https://github.com/beancount/beancount/blob/8c99bf0c8b254275d23058d4cd703c98c373f67e/beancount/core/number.py#L61), it's better to convert float arguments to strings first when passing into Decimal.  See the following example:

```
>>> f = 128.77
>>> from decimal import Decimal
>>> Decimal(f)
Decimal('128.770000000000010231815394945442676544189453125')
>>> Decimal(str(f))
Decimal('128.77')
```

The same thing happens when the float value is passed directly into the `D` helper function.

**Comment by blais** [comment]
https://docs.python.org/3/tutorial/floatingpoint.html
