### ISSUE TITLE
Missing plugins

### ISSUE THREAD

**Issue by tino** [beancount/beancount#804]
In the docs (eg. https://beancount.github.io/docs/how_we_share_expenses.html) there are links to the `divert_expenses` plugin, with a link to http://github.com/beancount/beancount/tree/master/beancount/plugins/divert_expenses.py. Same for `split_expenses`.

Those files don't exist on master. They do on V2, eg. https://github.com/beancount/beancount/blob/v2/beancount/plugins/split_expenses.py. 

I also can't find when or why they were deleted. `git log --all --full-history -- beancount/plugins/split_expenses.py` shows:
```
commit 53b6427126b69212a5f1966d7a24a2ae19b5553a
Merge: 05149d0d3 5212c005b
Author: blais <blais@furius.ca>
Date:   Sun Apr 30 15:46:25 2023 -0400

    (Merge branch 'v2', with lint)
```
as last commit, but it's not deleted there. (Although that is a merge commit, something went wrong in the merge?)

**Comment by blais** [comment]
The files have moved to the beanlabs repo. I should update the docs.

**Comment by tino** [comment]
Ah okay. And what is the recommended way to use plugins that are in there? Just download the files and add them locally?

(And out of curiosity, any idea why I couldn't find the commit where they were deleted?)

**Comment by blais** [comment]
Add the path to your PYTHONPATH. That's what I do. I don't deal with packaging other than Beancount itself.
