### ISSUE TITLE
New functionality suggestion: Optionally write a source for entry in  printer.print_entries

### ISSUE THREAD

**Issue by Ev2geny** [beancount/beancount#807]
I found it very useful to optionally enrich functionality of `printer.print_entries` to be able to add source file and line number in a format interpretable as a message location for Emacs, VSCode. 

This is very useful for "debugging" of beancount ledger especially in multi file setup. as it allows to immediately go to the file and line number in question by clicking on the message location.

**Example:**

![file_source](https://github.com/beancount/beancount/assets/59611075/5c6a121a-7905-4aa8-8690-740ef5f60ebd)

As this only useful for "debugging" it needs to be commented out by a semicolon, so it does not get parsed again if output  of a printer is sent again to parser

Would be nice to have it added as a standard feature.

I have a concept working for my purposes (this [commit ](https://github.com/Ev2geny/beancount/commit/8f4fe20511cefd5c4dc8045fbfb2128be02f5b59))

**Questions:** 
1) would you accept this as a pull request, provided I add unit tests and whatever else is needed
2) I now have done changes against v2. Is this OK? Or does it have to be against v3? 

P.S. in beancount discussions my name is **Chary**

**Comment by blais** [comment]
Sure! Why not. Send a PR to branch "master".

**Comment by dnicolodi** [comment]
Looking at the commit with the proposed implementation, I find the changes too intrusive for a debug functionality. I believe you can get the same result with the `; source:` comment in the line immediately preceding or following. In this case, you just need to modify `print_entries()`.

**Comment by Ev2geny** [comment]
@dnicolodi , thanks! 
It makes sense

**Comment by blais** [comment]
See #811
