### ISSUE TITLE
Ymonth returns date instead of year,month

### ISSUE THREAD

**Issue by pallavg** [beancount/beancount#808]
I was expecting Ymonth(date) to return 20XX-XX (year-month) but it returns a date (1st of the month). The Year(), month(), day() work OK. The screenshot below shows the issue.

![Screenshot 2024-03-02 163033](https://github.com/beancount/beancount/assets/12074568/874ab84f-53ce-4883-bb9a-f4d42cdc6d8d)

**Comment by blais** [comment]
Just on my phone now so I can't check but a good guess is that the data
type is a date with three first far and not a string, and a date cannot not
have a day

**Comment by dnicolodi** [comment]
Thanks for your report. However, things seem to be working as expected. Also `beancount.query` has been moved to the `beanquery` project https://github.com/beancount/beanquery. Any further discussion should continue there.
