### ISSUE TITLE
Feature Request: Support Default Args for scripts_utils.ingest()

### ISSUE THREAD

**Issue by eliptus** [beancount/beancount#809]
For import scripts that call scripts_utils.ingest(), allow them to provide default values for args like `downloads` and `destination`.

**Comment by dnicolodi** [comment]
This seems to be a feature request about `beancount.ingest`. This part of Beancount has been moved to the `beangulp` project https://github.com/beancount/beangulp and reorganized. Please have a loot at how the importer framework evolved and open issue there is you think it is still relevant.
