### ISSUE TITLE
Reducing an asset and a liability

### ISSUE THREAD

**Issue by daugminas** [beancount/beancount#814]
I searched the issues and couldn't find this covered: can such a basic usecase not be properly covered?

Situation: assume a basic company accounting, dividend payout entries.

Normally, this would have follwing Dr/Cr entries:

Dividend allocation decision (this one is fine):
Equity:Retained earnings Dr (-)
Liabilities:Dividend Payable Cr (+)

Dividend payment (this fails):
Liabilities:Dividend Payable Dr (-)
Assets:Cash Cr (-)

Note that the payment of liability with cash (or bank) violates beancount rules, i.e. there cannot be two minuses. However, from Dr/Cr entry perspective this makes sense. How should one deal with this situation in beancount?

More generally, how would you cover an outstanding liability (i.e. liaibility reduction) with an asset (also a reduction) in beancount? Either I cannot get my head wrapped around this or this doesn't work?!

**Comment by blais** [comment]
https://docs.google.com/document/d/100tGcA4blh6KSXPRGCZpUlyxaRUwFHEvnz_k9DyZFn4/

We don't use Cr/Dr in Beancount. All accounts are signed the same. You put in the signs.
