### ISSUE TITLE
Status of the "improved inventory booking" project?

### ISSUE THREAD

**Issue by pkgw** [beancount/beancount#817]
First of all, thanks for making and maintaining Beancount — it's awesome!

I've been trying to handle some average-cost transactions in my Beancount ledgers, which has led me to dig into some of the docs regarding the "improved inventory booking" proposal. These docs are clear in saying that the proposal hasn't been fully realized yet ... but they're dated to 2014, and it at appears from the GitHub that development on V3 has been proceeding at a steady rate.

I do a lot of open-source development so I know how annoying it can be when people constantly pester you about new features, so I apologize if this is something that you've had to answer a lot of questions about. But I haven't been able to dig anything up in the GitHub traffic or other docs. So: would you be able to quickly summarize where things are at with this effort? If more work is needed, anything random contributors can do to help?

**Comment by blais** [comment]
v3: still a dream, no time at all to devote to it. I still use regularly and maintain Beancount in working condition (I really need it for my own use).

avgcost: the precision and transfers required is tricky to do for full generality.
I'd be surprised if i didn't already discuss it on the list. Look for average cost booking.

v3 might still happen on the next life change, or probably when I get excited enough about Rust and use it as an excuse to do that.

**Comment by pkgw** [comment]
Thanks for the update. I am quite a big Rust fan and I completely agree that it seems like it would be a great fit for Beancount!

**Comment by ThomasdenH** [comment]
I've been playing with the idea of rewriting part of Beancount or its tools in Rust for a long time! I fear I don't have enough knowledge of the internals let alone the new plans that I think that my contribution would be very helpful, but I would definitely want to collaborate if the project gets off the ground.

I've helped a bit on `https://github.com/twilco/beancount` actually. Who knows, I might put some work in it again.
