### ISSUE TITLE
Feature request: Include Week and yearly Quarter number in BQL

### ISSUE THREAD

**Issue by simonhughxyz** [beancount/beancount#823]
It would be nice to get, filter and group by week and yearly quarter number in BQL to complement the already existing year and month.

For example:
If I want to find out what my quarterly earnings are I could do
``` sql
SELECT year, quarter, CONVERT(SUM(position), 'USD', date) AS balance
WHERE account ~ 'Income'
GROUP BY year, quarter
```

**Comment by simonhughxyz** [comment]
So I missed that `QUARTER()` is already a available function, but I can't find an equivalent `WEEK()` function. A function that could extract the week number of the year.

**Comment by dnicolodi** [comment]
beanquery recently gained the `date_trunc()` and `date_part()` functions. They are modeled after the PostgreSQL functions with the same names https://www.postgresql.org/docs/current/functions-datetime.html
