### ISSUE TITLE
Regarding the installation issue of bean-report

### ISSUE THREAD

**Issue by JmPotato** [beancount/beancount#832]
After completing the installation using pip with the latest 3.0 version, the current command line tool seems only to include the following tools:

![](https://github.com/beancount/beancount/assets/1446531/56b27826-b8f7-49fd-acfd-c657c25390cb)

After searching and digging into the code, I found no installation method for `bean-report`. Did I make a mistake somewhere? If I want to use `bean-report`, how should I install it if it's not included in the beancount installation?

**Comment by korrat** [comment]
`bean-report` has been removed in https://github.com/beancount/beancount/commit/a7c4f14f083de63e8d4e5a8d3664209daf95e1ec. Instead you can use [Fava] or `bean-query`, which has moved to [Beanquery] in https://github.com/beancount/beancount/commit/3db1836afa01205eb6077f3ce7ff0250b1f67b7e.

[Beanquery]: https://github.com/beancount/beanquery
[Fava]: https://github.com/beancount/fava

**Comment by JmPotato** [comment]
> `bean-report` has been removed in https://github.com/beancount/beancount/commit/a7c4f14f083de63e8d4e5a8d3664209daf95e1ec. Instead you can use [Fava] or `bean-query`, which has moved to [Beanquery] in https://github.com/beancount/beancount/commit/3db1836afa01205eb6077f3ce7ff0250b1f67b7e.
> 
> 
> 
> [Beanquery]: https://github.com/beancount/beanquery
> 
> [Fava]: https://github.com/beancount/fava

Thanks for the information! I will close this issue then.

**Comment by perchard** [comment]
hm what about the other binaries though, e.g. bean-extract? i also only see binaries for bean-check, bean-doctor, bean-example, bean-format, and treeify

**Comment by perchard** [comment]
I think the confusion is due to the fact that the instructions for installing v2 now install v3 since that was merged, and v3 doesn't include bean-report and many other binaries included in v2 and referenced in the docs.

**Comment by blais** [comment]
Moved to beangulp. beancount is just the core project now.

**Comment by hartzell** [comment]
Apologies for the late followup, but wanted to fact check @blais' [comment above on Jul 1, 2024](https://github.com/beancount/beancount/issues/832#issuecomment-2201607738).

I don't see any sign of bean-report in the current head of the beangulp project, nor in a bit of git spelunking through the beangulp history.

**Comment by blais** [comment]
That was in v2
Now deprecated and removed

**Comment by blais** [comment]
See mailing list
Bean report has been deprecated with v3
