### ISSUE TITLE
oauth2client has been deprecated for several years

### ISSUE THREAD

**Issue by adrien-n** [beancount/beancount#837]
Hi,

There are several uses of oauth2client in beancount and that package has unfortunately been abandonned or, rather, put in low-maintenance mode. After a few years in that state, cracks have started appearing and it would be interesting to migrate away from it. I've been working on removing the python-oauth2client package in Ubuntu and I know someone independently started that in Debian (but it's moving more slowly and the incentive is not as high).

It looks like the places this library is used are mainly beancount/tools/sheet_upload.py, or under experiments, or tools/update_options.py.

Upstream (i.e. google) recommendation is to use https://google-auth.readthedocs.io/ and http://oauthlib.readthedocs.io/ .

**Comment by blais** [comment]
Lgtm! Thank you
Sounds like you know a lot about this. A patch with the proper new way to
do this would be amazing.

**Comment by adrien-n** [comment]
Unfortunately I'm not that familiar with these. I mostly started as oauth2client is using now-removed functions from pyopenssl (and I tend to self-host rather than use google services).

That being said, I've noticed that there seems to be some API overlap. For instance, it seems service_account can be imported from google-auth too. That sounds worth a try.

**Comment by dnicolodi** [comment]
The current version of beancount does not install anything that depends on `oauth2client` therefore it is unclear to me how the use of `oauth2client` in some development tools (which AFAIK are not even included in source distributions) affects Debian (or anyone else).

**Comment by blais** [comment]
Only in v2 indeed.
```
lumia [git|master]:~/p/beancount$ rg oauth2client --no-heading
CHANGES:3628:    * oauth2client
CHANGES:3725:    * oauth2client
tools/update_options.py:20:# TODO(blais, 2023-11-18): oauth2client is deprecated.
tools/update_options.py:21:from oauth2client import service_account
experiments/docs_rst/download_docs.py:30:# TODO(blais, 2023-11-18): oauth2client is deprecated.
experiments/docs_rst/download_docs.py:31:from oauth2client import service_account
experiments/docs_rst/old/docs.py:18:# TODO(blais, 2023-11-18): oauth2client is deprecated.
experiments/docs_rst/old/docs.py:19:from oauth2client import service_account
lumia [git|master]:~/p/beancount$ git st
lumia [git|master]:~/p/beancount$ git co v2
Switched to branch 'v2'
lumia [git|v2]:~/p/beancount$ rg oauth2client --no-heading
beancount/scripts/deps.py:52:        check_import("oauth2client"),
tools/update_options.py:19:from oauth2client import service_account
beancount/tools/sheets_upload_test.py:8:# Skip the tests if oauth2client is not available.
beancount/tools/sheets_upload_test.py:12:oauth2client = pytest.importorskip("oauth2client")
beancount/tools/sheets_upload.py:36: * oauth2client
CHANGES:3598:    * oauth2client
CHANGES:3695:    * oauth2client
experiments/docs_rst/download_docs.py:29:from oauth2client import service_account
experiments/docs_rst/old/docs.py:17:from oauth2client import service_account
requirements.txt:9:oauth2client>=4.0
```
Not going to change v2, v2 is dead.  
Maybe if a patch doing that and only that I'd patch it, but other than that won't spent a second on it.

**Comment by adrien-n** [comment]
Indeed, as far as installed binaries go, the sheet_upload.py has been moved out of beancount a few months ago. I got confused as I took a first look at this several weeks ago.

In any case, one way or another, the library is going away and the scripts in v3 will break but hopefully, it will be enough to simply change the import as I outlined above.

**Comment by dnicolodi** [comment]
> In any case, one way or another, the library is going away

How can published Python packages go away? The package may be removed from Debian or Ubuntu, but I don't think anyone using the development tools using `oauth2client` uses the distribution package for the library. Functionality wise, I think it is unlikely that the basic functionality used by these scripts will completely break any time soon.

**Comment by adrien-n** [comment]
It uses APIs recently removed from pyopenssl and there are two possible
outcomes: removed from distributions, or remains but (partly?) stops
working.
