### ISSUE TITLE
run queries in my own python script with beancount 3.0.0 ?

### ISSUE THREAD

**Issue by uherbst** [beancount/beancount#845]
Hi all,

until beancount 2.3.6, I was able to run queries in a python script with:

from beancount.loader import load_file
from beancount.query.query import run_query

In beancount 3.0.0, I can't find any query option ? (installed with "pip install beancount"). 
Is there a new way to run queries in python ?

Thank you
Uli

**Comment by dnicolodi** [comment]
bean-query and the associated Python API has been moved to the the beanquery project. You can install it with `pip install beanquery` and change your imports from `from beancount.query import x` to `from beanquery import x`. The API exposed by beanquery is almost identical to the one exposed by `beancount.query` with some tiny differences. This issue https://github.com/beancount/beanquery/issues/191 has most of the details.
