### ISSUE TITLE
wrong auto-balance calculation when one leg is omitted

### ISSUE THREAD

**Issue by piengeng** [beancount/beancount#853]
```beancount
2024-09-01 open Equity:Opening-Balances USD
2024-09-01 open Assets:Cash:USD  USD
2024-09-01 open Expenses:US:Market:One  USD
2024-09-01 open Expenses:US:Market:Two  USD

2024-09-02 pad Assets:Cash:USD Equity:Opening-Balances
2024-09-03 balance Assets:Cash:USD     3 USD

2024-09-05 * "something"
  Expenses:US:Market:One               1 USD
  Expenses:US:Market:Two            0.95 USD
  Assets:Cash:USD                   ;-1.95 USD ; IF leave blank, the balance is OFF!
```

the balance calculation is wrong, I've not looked into the core code yet, Assets:Cash:USD's balance should be 1.05 instead of 1 when last leg left hanging? or is this the intended feature? if I change Market:One's 1 USD to 1.00 USD, it's 1.05 again

i'm at v2.3.6, v3 still missing a lot of previous cli apps.

**Comment by dnicolodi** [comment]
Everything is working as expected, as far as I can tell. beancount infers the quantization to use (number of decimal digits) from (roughly) the most common number of digits used associated with a given currency in the output. If you want cents quantization, you need to write (most) quantities with the right number of decimal digits.

> v3 still missing a lot of previous cli apps.

Some command line tools have migrated to independent projects: beanquery, beanprive. beangulp is an evolution of `beancount.ingest` but not a drop-in replacement. Other command lines tools have been discontinued.

**Comment by piengeng** [comment]
i've to disagree on the assessment
on calculation alone: 3 - (1 + 0.95) should equal 1.05 as balance not 1
3 - (1.00 + 0.95) equals 1.05 is correct, the basic in mathematic should at least be respected in accounting, no?

**Comment by blais** [comment]
Daniele is right, but the right thing to do eventually is to add options to allow users to specify the precision used in inference.
These little test programs aren't representative of real input; in a real input file you'd have a ton more x.xx numbers and this problem wouldn't show up. It's only because it's trying to automatically infer the precision here that this fails.

**Comment by piengeng** [comment]
that's actually modification of my actual input, sorry for my point of view, instead of typing `1.00` to make the auto-balance works correctly, i typed `1`, partly `1` `1.` `1.0` `1.00` are all the same in most people point of view. and from these 4 manual/text input by human. only 1 calculate correctly.
