### ISSUE TITLE
add a bean-report stub script

### ISSUE THREAD

**Issue by WolfgangFahl** [beancount/beancount#855]
https://github.com/beancount/beancount/issues/832

is unfortunately closed. As a newbie for beancount i am frustrated since i am following https://beancount.github.io/docs/tutorial_example.html#converting-to-ledger-input

```bash
bean-report example.beancount ledger > example.lgr
```

does not work and i have a hard time finding out what to do now. 
the beancount project seems to provide:
```
[project.scripts]
bean-check = "beancount.scripts.check:main"
bean-doctor = "beancount.scripts.doctor:main"
bean-example = "beancount.scripts.example:main"
bean-format = "beancount.scripts.format:main"
treeify = "beancount.tools.treeify:main"
```

the beangulp project has no such entry

My suggestiong is to add a stub-script bean-report which will provide a message/links on how to proceed if one expects bean-report (V2) while V3 works differently

**Comment by edoardob90** [comment]
This is just a suggestion (or workaround): why don't you create a virtual environment with Beancount v2 to follow the tutorial? Assuming you want to keep both versions around.

After you have the environment, you can install v2 with

```bash
pip install git+https://github.com/beancount/beancount@2.3.6
```

**Comment by WolfgangFahl** [comment]
@edoardob90 
my usecases is the https://github.com/WolfgangFahl/pynomina convert project. I am currently generating .beancount files with V3 but to test i am using e.g. fava (not V3) and bean-check. I have no clue of the implications and incompatibilities because i had hoped to use beancount in a black-box style without having to fiddle with too many technical details. The bean-report issue i opened here is only one of the confusions i found in the current transition situation. 

I started with a virtual env for pynomina due to piecash's SQL Alchemy 1.5 dep - i removed that in the meantime and would hate to have to stay virtual again for beancount. The main question is whether V3 and V2 have compatible beancount markup.

**Comment by dnicolodi** [comment]
> My suggestiong is to add a stub-script bean-report which will provide a message/links on how to proceed if one expects bean-report (V2) while V3 works differently

Adding stub scripts would be an even worse user experience. Effort should be dedicated instead to update the documentation. No one have contributed updates to the documentation and the core developers do not have free time to dedicate to it.

If you want to convert beancount format to ledger format, you should use the tools provided by this project https://github.com/beancount/beancount2ledger

> The main question is whether V3 and V2 have compatible beancount markup.

beancount 3.0.0 parses correctly everything that parses correctly in beancount 2.3. The other way around is not true: 3.0 added some features that are not backward compatible. However, the documentation covers only beancount 2.3 syntax, so you should be fine.
