### ISSUE TITLE
pip install on mac seems to be missing dependancies. 

### ISSUE THREAD

**Issue by the1gofer** [beancount/beancount#857]
I installed using the command  `sudo -H python3 -m pip install beancount`, which, at first, seems to have worked.  However, when going through the tutorial, i began to notice that web-bean gave the `zsh: command not found: web-bean` and `bean-report --help` also errored with `zsh: command not found: bean-report`.

**Comment by dnicolodi** [comment]
`bean-report` has been removed in beancount 3.0. `web-bean` has never been part of beancount.
