### ISSUE TITLE
document can't handle backslash in filename

### ISSUE THREAD

**Issue by trim21** [beancount/beancount#871]
example:

```py
from beancount import print_entries
from beancount.loader import load_string

row = r"""
2014-06-08 document Assets:Account1 "D:\a\beancount\beancount\path\to\document.csv"
"""

print(repr(load_string(row)[0][0].filename))
print_entries(load_string(row)[0])
```

here filename is `'D:\\a\x08eancount\x08eancountpath\todocument.csv'` instead of expected `'D:\a\beancount\beancount\path\to\document.csv'`

**Comment by dnicolodi** [comment]
This is working as expected. You need to escape backward slashes in strings: `\` should be encoded as `\\`.

**Comment by blais** [comment]
That's correct. Doesn't Windows accept / as well? I thought it did.

**Comment by trim21** [comment]
nevermind, printter print filename with single backslash so I thought it's expected to have single backslash
