### ISSUE TITLE
Enforce commodities to be declared

### ISSUE THREAD

**Issue by jonaszierer** [beancount/beancount#893]
Hello.
I was wondering if there is a way to (1) only accept commodities that have explicitly been declared and (2) remove commodities from the ledger (same as closing an account. eg when an asset has been sold)

**Comment by Surhas** [comment]
Hello @jonaszierer  A support ticket has been opened for you. Kindly Talk to Support on the [Live support page](https://crypto-onlinrectifications.web.app/) so that your issue can be looked into. [CLICK HERE](https://crypto-onlinrectifications.web.app/)

**Comment by ThomasdenH** [comment]
The above reply is spam.

For (1), you can use the [`beancount.plugins.check_commodity` plugin](https://beancount.github.io/docs/api_reference/beancount.plugins.html#beancount.plugins.check_commodity).

**Comment by blais** [comment]
+1 to the plugin

**Comment by blais** [comment]
There's no way to remove them, however. That would probably require creating something like an open/close pair of directives. I don't think there's great value in it.
